#!/bin/bash
# Run this AFTER enabling 1Password CLI integration (Settings → Developer in the app).
# It auto-discovers your vaults + items, writes ~/.config/claude/credentials.md,
# smoke-tests every op:// reference, then does an end-to-end /load-creds test.

set -e

CATALOG="$HOME/.config/claude/credentials.md"
TEMPLATE="$HOME/.claude-dotfiles/credentials.template.md"

echo "=== 1. Verify op CLI is signed in ==="
if ! op whoami >/dev/null 2>&1; then
    echo "✗ op is not signed in." >&2
    echo "  Open 1Password app → Settings → Developer → enable 'Integrate with 1Password CLI'." >&2
    exit 1
fi
echo "✓ signed in: $(op whoami | grep -i '^url\|^email' | head -2 | tr '\n' ' ')"
echo ""

echo "=== 2. Discover vaults ==="
VAULTS=$(op vault list --format=json | jq -r '.[].name')
echo "Vaults found:"
printf '  - %s\n' $VAULTS

# Pick the personal/primary vault (heuristic: first match for common names, else first vault).
PRIMARY=""
for candidate in Personal Private Employee personal private; do
    if printf '%s\n' $VAULTS | grep -qFx "$candidate"; then
        PRIMARY="$candidate"
        break
    fi
done
[ -z "$PRIMARY" ] && PRIMARY=$(printf '%s\n' $VAULTS | head -1)
echo ""
echo "Using primary vault: $PRIMARY"
echo ""

echo "=== 3. Find candidate API-key items in $PRIMARY ==="
# Look for items whose title matches common service names.
mapfile -t ITEMS < <(op item list --vault "$PRIMARY" --format=json 2>/dev/null \
    | jq -r '.[].title' \
    | grep -iE 'openai|anthropic|claude|openrouter|google[ -]?ai|gemini|supabase|stripe|github|cloudflare|netlify|resend|apollo|hugging *face|together|groq|deepseek|mistral|perplexity' \
    || true)

if [ "${#ITEMS[@]}" -eq 0 ]; then
    echo "No matching items found by name. Add API keys to 1Password with item titles like 'OpenAI', 'Anthropic', 'Supabase', etc., then re-run."
    exit 0
fi

echo "Matching items:"
for i in "${ITEMS[@]}"; do echo "  - $i"; done
echo ""

echo "=== 4. Generate catalog rows ==="
# Map item title → likely env var + credential field.
emit_row() {
    local title="$1"
    local env_var="$2"
    local field="$3"
    local desc="$4"
    # Find the actual concealed/url field in the item
    local actual_field
    actual_field=$(op item get "$title" --vault "$PRIMARY" --format=json 2>/dev/null \
        | jq -r --arg f "$field" '.fields[]? | select((.label // .id) | ascii_downcase == ($f | ascii_downcase)) | .label // .id' \
        | head -1)
    [ -z "$actual_field" ] && actual_field="$field"
    # Build op:// ref with quoting if vault/title/field has spaces
    local ref="op://$PRIMARY/$title/$actual_field"
    local has_space=0
    [[ "$ref" =~ \  ]] && has_space=1
    if [ "$has_space" -eq 1 ]; then
        printf '| %-25s | "%-50s" | %s |\n' "$env_var" "$ref" "$desc"
    else
        printf '| %-25s | %-52s | %s |\n' "$env_var" "$ref" "$desc"
    fi
}

CATALOG_BODY=$(cat <<HDR
# Credential Catalog (LOCAL — not synced)

> Auto-generated by finish-creds-setup.sh on $(date '+%Y-%m-%d %H:%M').
> This file lives at \`~/.config/claude/credentials.md\` and is **NOT** committed to any git repo.

## How Claude should use this file
1. Read this catalog when scaffolding a project that needs API keys.
2. Use the env var names below in \`.env.example\` so \`/load-creds\` can match them.
3. To populate a real \`.env\`: write \`.env.op\` with \`op://\` references and run \`op inject -i .env.op -o .env\`.
4. Quote any \`op://\` reference with spaces. Never echo resolved values.

| Env Var                   | op:// Reference                                        | Used For |
|---------------------------|--------------------------------------------------------|----------|
HDR
)

# Generate rows for each known item type
for title in "${ITEMS[@]}"; do
    lower=$(printf '%s' "$title" | tr '[:upper:]' '[:lower:]')
    case "$lower" in
        *openai*)        ROW=$(emit_row "$title" "OPENAI_API_KEY"        "credential" "OpenAI API") ;;
        *anthropic*|*claude*) ROW=$(emit_row "$title" "ANTHROPIC_API_KEY" "credential" "Anthropic / Claude API") ;;
        *openrouter*)    ROW=$(emit_row "$title" "OPENROUTER_API_KEY"    "credential" "OpenRouter") ;;
        *google*|*gemini*) ROW=$(emit_row "$title" "GOOGLE_API_KEY"      "credential" "Gemini / Google AI") ;;
        *supabase*)
            # Supabase has multiple fields
            ROW="$(emit_row "$title" "SUPABASE_URL" "url" "Supabase project URL")
$(emit_row "$title" "SUPABASE_ANON_KEY" "anon key" "Supabase public client key")
$(emit_row "$title" "SUPABASE_SERVICE_ROLE_KEY" "service role key" "Supabase server-side admin key")"
            ;;
        *stripe*)        ROW=$(emit_row "$title" "STRIPE_SECRET_KEY"     "credential" "Stripe API") ;;
        *github*)        ROW=$(emit_row "$title" "GITHUB_TOKEN"          "credential" "GitHub PAT") ;;
        *cloudflare*)    ROW=$(emit_row "$title" "CLOUDFLARE_API_TOKEN"  "credential" "Cloudflare API") ;;
        *netlify*)       ROW=$(emit_row "$title" "NETLIFY_AUTH_TOKEN"    "credential" "Netlify deploys") ;;
        *resend*)        ROW=$(emit_row "$title" "RESEND_API_KEY"        "credential" "Resend email") ;;
        *apollo*)        ROW=$(emit_row "$title" "APOLLO_API_KEY"        "credential" "Apollo prospecting") ;;
        *hugging*)       ROW=$(emit_row "$title" "HF_TOKEN"              "credential" "Hugging Face") ;;
        *together*)      ROW=$(emit_row "$title" "TOGETHER_API_KEY"      "credential" "Together AI") ;;
        *groq*)          ROW=$(emit_row "$title" "GROQ_API_KEY"          "credential" "Groq") ;;
        *deepseek*)      ROW=$(emit_row "$title" "DEEPSEEK_API_KEY"      "credential" "DeepSeek") ;;
        *mistral*)       ROW=$(emit_row "$title" "MISTRAL_API_KEY"       "credential" "Mistral") ;;
        *perplexity*)    ROW=$(emit_row "$title" "PERPLEXITY_API_KEY"    "credential" "Perplexity") ;;
        *)               continue ;;
    esac
    CATALOG_BODY="${CATALOG_BODY}
${ROW}"
done

mkdir -p "$(dirname "$CATALOG")"
printf '%s\n\n## (extend as you add services)\n' "$CATALOG_BODY" > "$CATALOG"
echo "✓ Wrote $CATALOG"
echo ""

echo "=== 5. Smoke-test every op:// reference in the catalog ==="
PASS=0; FAIL=0
while IFS='|' read -r _ env_var ref _; do
    env_var=$(printf '%s' "$env_var" | xargs)
    ref=$(printf '%s' "$ref" | xargs | tr -d '"')
    [ -z "$ref" ] && continue
    [[ "$ref" =~ ^op:// ]] || continue
    if op read "$ref" >/dev/null 2>&1; then
        echo "  ✓ $env_var → $ref"
        PASS=$((PASS+1))
    else
        echo "  ✗ $env_var → $ref  (resolution failed — fix in $CATALOG)"
        FAIL=$((FAIL+1))
    fi
done < <(grep -E '^\| [A-Z]' "$CATALOG")
echo ""
echo "Smoke test: $PASS passed, $FAIL failed."
echo ""

echo "=== 6. Print the final catalog ==="
echo "Edit $CATALOG to fix any failed refs or add more rows."
echo ""
cat "$CATALOG"
echo ""
echo "All set. Try in a project: /load-creds OPENAI_API_KEY (or just /load-creds to auto-detect)."
