#!/bin/bash
# Regression suite for the secret-protection chain:
#   scripts/secret-scan.sh + the pre-commit / pre-push hooks generated by
#   scripts/install-git-hooks.sh.
#
# Run: bash scripts/hooks/test-secret-scan.sh          (exit 0 = all pass, 1 = failure)
#
# Every case here maps to a defect that was MEASURED in the live chain on 2026-08-01.
# Before this suite existed the chain had zero automated coverage, which is precisely why
# a fail-open pre-push hook survived in a repo that auto-pushes to a public remote.
#
# HERMETIC: overrides HOME so the generated hooks resolve to the fixture, and neutralizes
# global/system git config so the suite cannot borrow the developer's identity or
# init.defaultBranch (a fixture that silently uses your global identity passes locally and
# dies on CI). Model: scripts/hooks/test-lint-skill-size.sh.
#
# NOTE ON FIXTURE SECRETS: every fake credential is assembled at RUNTIME from fragments.
# This file is tracked, and the CI job scans the whole tree - a literal token in the source
# would make the repo's own full-tree scan red forever.

set -u

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCAN="$REPO/scripts/secret-scan.sh"
INSTALL="$REPO/scripts/install-git-hooks.sh"

PASS=0; FAIL=0
chk() { # chk <name> <got> <want>
    if [ "$2" = "$3" ]; then
        PASS=$((PASS + 1)); printf '  PASS  %s\n' "$1"
    else
        FAIL=$((FAIL + 1)); printf '  FAIL  %s   got=<%s> want=<%s>\n' "$1" "$2" "$3"
    fi
}

# Fake credentials, assembled so no matchable literal appears in this file's bytes.
_AK=$(printf '%s%s' 'AK' 'IA')
SECRET="${_AK}ABCDEFGHIJKLMNOP"

WORK=$(mktemp -d) || { echo "mktemp failed"; exit 1; }
cleanup() { chmod -R u+rwX "$WORK" 2>/dev/null; rm -rf "$WORK"; }
trap 'cleanup' EXIT
trap 'cleanup; exit 3' HUP INT TERM

export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null
export GIT_AUTHOR_NAME=test GIT_AUTHOR_EMAIL=test@example.invalid
export GIT_COMMITTER_NAME=test GIT_COMMITTER_EMAIL=test@example.invalid

# ---------------------------------------------------------------------------
echo "== scanner unit cases =="
U="$WORK/unit"; mkdir -p "$U"; cd "$U" || exit 1
git init -q .

# 1. The live bypass: index holds the secret, worktree holds harmless bytes.
printf '%s\n' "$SECRET" > leak.txt; git add leak.txt; printf 'harmless\n' > leak.txt
bash "$SCAN" --staged >/dev/null 2>&1
chk "staged reads INDEX blobs, not worktree" "$?" "2"

# 2. Failure precedence 3 > 2: an unreadable file MUST outrank a real hit.
printf '%s\n' "$SECRET" > hit.txt
printf '%s\n' "$SECRET" > noread.txt; chmod 000 noread.txt
bash "$SCAN" hit.txt noread.txt >/dev/null 2>&1
chk "unreadable + real hit exits 3 (3 > 2)" "$?" "3"
chmod 644 noread.txt

# 3. `*.git/*` used to swallow ordinary paths containing ".git".
mkdir -p vendor/leak.git; printf '%s\n' "$SECRET" > vendor/leak.git/secret.txt
bash "$SCAN" vendor/leak.git/secret.txt >/dev/null 2>&1
chk "vendor/leak.git/ is NOT treated as a git dir" "$?" "2"

printf '%s\n' "$SECRET" > .git/COMMIT_EDITMSG
bash "$SCAN" .git/COMMIT_EDITMSG >/dev/null 2>&1
chk "a real .git/ path is still skipped" "$?" "0"

# 4. Output contract: signal is the exit code; hits go to stderr; stdout stays empty.
out=$(bash "$SCAN" hit.txt 2>/dev/null)
chk "stdout stays empty on a hit" "${#out}" "0"
err=$(bash "$SCAN" hit.txt 2>&1 >/dev/null)
chk "stderr carries the banner" "$(printf '%s' "$err" | grep -c 'BLOCKED: secret detected')" "1"
chk "no literal dollar-quote spliced into output" "$(printf '%s' "$err" | grep -c "\$'")" "0"

# 5. Filenames that broke the old `FILES="$*"` + unquoted expansion.
printf '%s\n' "$SECRET" > "$(printf 'we\nird name.txt')"
bash "$SCAN" "$(printf 'we\nird name.txt')" >/dev/null 2>&1
chk "filename with a newline and a space" "$?" "2"
printf '%s\n' "$SECRET" > 'star*.txt'
bash "$SCAN" 'star*.txt' >/dev/null 2>&1
chk "filename with a glob char is literal" "$?" "2"
printf '%s\n' "$SECRET" > 'pipe|bar.txt'
bash "$SCAN" 'pipe|bar.txt' >/dev/null 2>&1
chk "filename with the sed delimiter" "$?" "2"

# 6. Contract edges CI and the hooks rely on.
printf 'nothing to see\n' > clean.txt
bash "$SCAN" clean.txt >/dev/null 2>&1
chk "clean file exits 0" "$?" "0"
bash "$SCAN" definitely-absent.txt >/dev/null 2>&1
chk "absent path exits 0 (CI drops its -f guard)" "$?" "0"
bash "$SCAN" >/dev/null 2>&1
chk "no arguments exits 3" "$?" "3"

# ---------------------------------------------------------------------------
echo "== false-positive gate: the real repository must stay clean =="
# If this ever fails, a regex or filter change made the gate unusable: it would jam every
# commit in this repo AND silently block the async auto-push.
( cd "$REPO" && git ls-files -z | xargs -0 bash "$SCAN" ) >/dev/null 2>&1
chk "full tree of $(basename "$REPO") scans clean" "$?" "0"

# ---------------------------------------------------------------------------
echo "== end-to-end hook cases =="
FIXHOME="$WORK/home"; mkdir -p "$FIXHOME/.claude-dotfiles"
cp -R "$REPO/scripts" "$FIXHOME/.claude-dotfiles/scripts"
R="$FIXHOME/.claude-dotfiles"
git init -q "$R"; git init -q --bare "$WORK/remote.git"
cd "$R" || exit 1
git remote add origin "$WORK/remote.git"
HOME="$FIXHOME" bash "$INSTALL" >/dev/null 2>&1
chk "installer generated pre-push" "$([ -x "$R/.git/hooks/pre-push" ] && echo yes)" "yes"
chk "installer generated pre-commit" "$([ -x "$R/.git/hooks/pre-commit" ] && echo yes)" "yes"
chk "pre-commit keeps secret-scan TERMINAL via exec" \
    "$(grep -cE '^exec .*secret-scan\.sh.* --staged' "$R/.git/hooks/pre-commit")" "1"
# Order is load-bearing: the size lint must run BEFORE the exec, because nothing after an
# exec is reachable. Compare positions rather than a hardcoded line number so a comment
# edit cannot silently turn this assertion into a no-op.
_lint_ln=$(grep -n 'lint-skill-size\.sh' "$R/.git/hooks/pre-commit" | head -1 | cut -d: -f1)
_exec_ln=$(grep -nE '^exec .*secret-scan\.sh' "$R/.git/hooks/pre-commit" | head -1 | cut -d: -f1)
chk "size lint runs BEFORE the terminal exec" \
    "$([ -n "$_lint_ln" ] && [ -n "$_exec_ln" ] && [ "$_lint_ln" -lt "$_exec_ln" ] && echo yes)" "yes"

BR=$(git symbolic-ref --short HEAD)   # never assume master vs main
rgit() { git --git-dir="$WORK/remote.git" "$@"; }

# A. A clean push must still work. A gate that blocks everything is not a gate.
printf 'hello\n' > a.txt; git add a.txt; HOME="$FIXHOME" git commit -qm clean
HOME="$FIXHOME" git push -q origin "$BR" >/dev/null 2>&1
chk "clean push succeeds" "$?" "0"
BASE=$(rgit rev-parse "$BR" 2>/dev/null)
chk "remote advanced to local HEAD" "$BASE" "$(git rev-parse HEAD)"

# B. The case that justified the whole range design: a secret added and then removed
#    before the tip. The tip tree is clean, so any tip-only scan reports success.
printf '%s\n' "$SECRET" > mid.txt; git add mid.txt
HOME="$FIXHOME" git commit -qm "add cfg" --no-verify >/dev/null
git rm -q mid.txt; HOME="$FIXHOME" git commit -qm "rm cfg" --no-verify >/dev/null
chk "tip tree really is clean" "$(git grep -l "$SECRET" HEAD 2>/dev/null | wc -l | tr -d ' ')" "0"
perr=$(HOME="$FIXHOME" git push origin "$BR" 2>&1); prc=$?
chk "middle-commit secret is rejected" "$([ "$prc" -ne 0 ] && echo yes)" "yes"
chk "rejection shows the scanner banner" "$(printf '%s' "$perr" | grep -c 'BLOCKED: secret detected')" "1"
chk "remote ref did NOT move" "$(rgit rev-parse "$BR")" "$BASE"

# C. A secret that exists only in a commit MESSAGE (no blob anywhere).
git reset -q --hard "$BASE"
printf 'ok\n' > c.txt; git add c.txt
HOME="$FIXHOME" git commit -qm "deploy key $SECRET" --no-verify >/dev/null
HOME="$FIXHOME" git push origin "$BR" >/dev/null 2>&1
chk "commit-message secret is rejected" "$([ "$?" -ne 0 ] && echo yes)" "yes"
chk "remote ref still did NOT move" "$(rgit rev-parse "$BR")" "$BASE"

# D. New branch: the old hook diffed against the worktree and enumerated zero files.
git reset -q --hard "$BASE"; git checkout -q -b leakbranch
printf '%s\n' "$SECRET" > n.txt; git add n.txt
HOME="$FIXHOME" git commit -qm new --no-verify >/dev/null
HOME="$FIXHOME" git push origin leakbranch >/dev/null 2>&1
chk "new-branch secret is rejected" "$([ "$?" -ne 0 ] && echo yes)" "yes"
chk "new branch was NOT created on the remote" \
    "$(rgit rev-parse leakbranch >/dev/null 2>&1 && echo present || echo absent)" "absent"

# E. A clean new branch must still push.
git checkout -q -b finebranch "$BASE"
printf 'fine\n' > f.txt; git add f.txt; HOME="$FIXHOME" git commit -qm fine >/dev/null
HOME="$FIXHOME" git push -q origin finebranch >/dev/null 2>&1
chk "clean new branch pushes" "$?" "0"
chk "clean new branch reached the remote" \
    "$(rgit rev-parse finebranch >/dev/null 2>&1 && echo present || echo absent)" "present"

# F. pre-commit must block the staged-index bypass end to end.
git checkout -q "$BR"
printf '%s\n' "$SECRET" > s.txt; git add s.txt; printf 'harmless\n' > s.txt
HOME="$FIXHOME" git commit -qm sneaky >/dev/null 2>&1
chk "pre-commit blocks a staged secret" "$([ "$?" -ne 0 ] && echo yes)" "yes"

# ---------------------------------------------------------------------------
echo
echo "---- $PASS passed, $FAIL failed ----"
[ "$FAIL" -eq 0 ] || exit 1
exit 0
