#!/bin/bash
# Regression suite for the secret-protection chain:
#   scripts/secret-scan.sh + the pre-commit / pre-push hooks generated by
#   scripts/install-git-hooks.sh.
#
# Run: bash scripts/hooks/test-secret-scan.sh          (exit 0 = all pass, 1 = failure)
#
# Every case here maps to a defect that was MEASURED in the live chain on 2026-08-01.
# Before this suite existed the chain had zero automated coverage, which is precisely why
# a fail-open pre-push hook survived in a repo that auto-pushes to a public remote.
#
# HERMETIC: overrides HOME so the generated hooks resolve to the fixture, and neutralizes
# global/system git config so the suite cannot borrow the developer's identity or
# init.defaultBranch (a fixture that silently uses your global identity passes locally and
# dies on CI). Model: scripts/hooks/test-lint-skill-size.sh.
#
# NOTE ON FIXTURE SECRETS: every fake credential is assembled at RUNTIME from fragments.
# This file is tracked, and the CI job scans the whole tree - a literal token in the source
# would make the repo's own full-tree scan red forever.

set -u

# stdin is CLOSED for the whole suite (2026-08-03, round-4 review). Several cases invoke
# stale-handoff-guard.sh, which begins `HOOK_JSON=$(cat)` and therefore blocks FOREVER on an
# inherited stdin that never reaches EOF. Round 3 patched only the CI call site with
# `</dev/null`; that left every OTHER caller - a human in a pipeline, another workflow, an
# agent - able to hang the suite indefinitely. Reproduced: `sleep 400 | bash <suite>` was
# still running at 100s. Closing it here fixes the class rather than one call site.
exec </dev/null

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCAN="$REPO/scripts/secret-scan.sh"
INSTALL="$REPO/scripts/install-git-hooks.sh"

PASS=0; FAIL=0
chk() { # chk <name> <got> <want>
    if [ "$2" = "$3" ]; then
        PASS=$((PASS + 1)); printf '  PASS  %s\n' "$1"
    else
        FAIL=$((FAIL + 1)); printf '  FAIL  %s   got=<%s> want=<%s>\n' "$1" "$2" "$3"
    fi
}

# Fake credentials, assembled so no matchable literal appears in this file's bytes.
_AK=$(printf '%s%s' 'AK' 'IA')
SECRET="${_AK}ABCDEFGHIJKLMNOP"

WORK=$(mktemp -d) || { echo "mktemp failed"; exit 1; }
cleanup() { chmod -R u+rwX "$WORK" 2>/dev/null; rm -rf "$WORK"; }
trap 'cleanup' EXIT
trap 'cleanup; exit 3' HUP INT TERM

export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null
export GIT_AUTHOR_NAME=test GIT_AUTHOR_EMAIL=test@example.invalid
export GIT_COMMITTER_NAME=test GIT_COMMITTER_EMAIL=test@example.invalid

# ---------------------------------------------------------------------------
echo "== scanner unit cases =="
U="$WORK/unit"; mkdir -p "$U"; cd "$U" || exit 1
git init -q .

# 1. The live bypass: index holds the secret, worktree holds harmless bytes.
printf '%s\n' "$SECRET" > leak.txt; git add leak.txt; printf 'harmless\n' > leak.txt
bash "$SCAN" --staged >/dev/null 2>&1
chk "staged reads INDEX blobs, not worktree" "$?" "2"

# 2. Failure precedence 3 > 2: an unreadable file MUST outrank a real hit.
printf '%s\n' "$SECRET" > hit.txt
printf '%s\n' "$SECRET" > noread.txt; chmod 000 noread.txt
bash "$SCAN" hit.txt noread.txt >/dev/null 2>&1
chk "unreadable + real hit exits 3 (3 > 2)" "$?" "3"
chmod 644 noread.txt

# 3. `*.git/*` used to swallow ordinary paths containing ".git".
mkdir -p vendor/leak.git; printf '%s\n' "$SECRET" > vendor/leak.git/secret.txt
bash "$SCAN" vendor/leak.git/secret.txt >/dev/null 2>&1
chk "vendor/leak.git/ is NOT treated as a git dir" "$?" "2"

printf '%s\n' "$SECRET" > .git/COMMIT_EDITMSG
bash "$SCAN" .git/COMMIT_EDITMSG >/dev/null 2>&1
chk "a real .git/ path is still skipped" "$?" "0"

# 4. Output contract: signal is the exit code; hits go to stderr; stdout stays empty.
out=$(bash "$SCAN" hit.txt 2>/dev/null)
chk "stdout stays empty on a hit" "${#out}" "0"
err=$(bash "$SCAN" hit.txt 2>&1 >/dev/null)
chk "stderr carries the banner" "$(printf '%s' "$err" | grep -c 'BLOCKED: secret detected')" "1"
# The dollar-quote assertion is only meaningful on a file that hits BOTH lanes, because the
# corruption it names lives in the primary/PIN JOIN. Against a primary-only hit it asserted
# nothing at all.
_PJ=$(printf '%s%s %s%s' 'P' 'IN:' '4829' '13')
printf '%s\n%s\n' "$SECRET" "$_PJ" > bothlanes.txt
joinerr=$(bash "$SCAN" bothlanes.txt 2>&1 >/dev/null)
chk "a both-lanes file really hits both" \
    "$(printf '%s' "$joinerr" | grep -Ec 'bothlanes\.txt:[0-9]+:')" "2"
# HONEST SCOPE (round-5 finding): this runtime assertion CANNOT fail under bash, because bash
# expands `${x:+$'\n'}` correctly and this suite runs under bash. It is kept only as an
# output-sanity check, not as proof. The idiom splices literal characters under ZSH - and these
# scripts get probed and sourced from both - so the check that can actually catch a regression
# is STATIC, against the source. Reverting the explicit join now reddens the second line.
chk "join output carries no literal dollar-quote" "$(printf '%s' "$joinerr" | grep -c "\$'")" "0"
chk "source avoids the zsh-unsafe :+ dollar-quote idiom" "$(grep -c ":+\$'" "$SCAN")" "0"

# 5. Filenames that broke the old `FILES="$*"` + unquoted expansion.
printf '%s\n' "$SECRET" > "$(printf 'we\nird name.txt')"
bash "$SCAN" "$(printf 'we\nird name.txt')" >/dev/null 2>&1
chk "filename with a newline and a space" "$?" "2"
# An exit-code assertion CANNOT detect glob expansion here: a pattern always matches its own
# literal name, so an expanding scanner still reads the requested file and still exits 2.
# The observable difference is SCOPE - expansion drags in siblings. The decoy therefore
# carries its own secret, and the assertion is that only the REQUESTED path is reported.
printf '%s\n' "$SECRET" > 'star*.txt'
printf '%s\n' "$SECRET" > 'star-decoy.txt'
globerr=$(bash "$SCAN" 'star*.txt' 2>&1 >/dev/null)
chk "glob-named file is scanned" "$(printf '%s' "$globerr" | grep -c 'star\*\.txt')" "1"
chk "glob is NOT expanded to siblings" "$(printf '%s' "$globerr" | grep -c 'star-decoy')" "0"
printf '%s\n' "$SECRET" > 'pipe|bar.txt'
bash "$SCAN" 'pipe|bar.txt' >/dev/null 2>&1
chk "filename with the sed delimiter" "$?" "2"

# 6. Contract edges CI and the hooks rely on.
printf 'nothing to see\n' > clean.txt
bash "$SCAN" clean.txt >/dev/null 2>&1
chk "clean file exits 0" "$?" "0"
# CONTRACT CHANGED 2026-08-03 (round-2 review). This used to assert rc=0, on the rationale
# "CI drops its -f guard" - true of the DIFF-based CI job, which passed deleted paths and
# went red on every deletion-bearing push. That job no longer exists: the workflow now scans
# the full tree via `git ls-files`, so the rationale for the fail-open was already gone.
# A scanner told to scan ONE path that is not there, answering "clean", is exactly the
# "guard that cannot reach its target reports success" class. It now reports rc=3.
bash "$SCAN" definitely-absent.txt >/dev/null 2>&1
chk "a lone absent path is rc=3 (nothing was scanned, so nothing is proven)" "$?" "3"
# The deletion tolerance the old contract protected is preserved where it actually matters:
# a MIXED batch (the CI shape) stays green, because something really was scanned.
printf 'nothing to see\n' > mixed-present.txt
bash "$SCAN" mixed-present.txt definitely-absent.txt >/dev/null 2>&1
chk "an absent path alongside a scanned one stays rc=0 (CI deletion tolerance)" "$?" "0"
bash "$SCAN" >/dev/null 2>&1
chk "no arguments exits 3" "$?" "3"

# 7. End-of-options. A tracked file named like a flag must not switch the scanner's mode
#    and silently turn a full-tree scan into a scan of nothing.
printf '%s\n' "$SECRET" > './--staged'
bash "$SCAN" -- '--staged' >/dev/null 2>&1
chk "-- treats a flag-named file as a path" "$?" "2"
# Prove `--` is load-bearing, and that CI actually passes it. Without these two, deleting
# `--` from the workflow - or the scanner's `--)` arm - left the suite entirely green.
# Exit codes cannot tell these apart (this fixture has a staged secret, so mode-switching
# also exits 2). The discriminator is WHICH path gets reported.
_wq=$(bash "$SCAN" -- '--staged' 2>&1 >/dev/null)
_woq=$(bash "$SCAN" '--staged' 2>&1 >/dev/null)
chk "with -- the flag-named FILE is reported" "$(printf '%s' "$_wq" | grep -c -- '--staged:')" "1"
chk "without -- it switches mode and reports the index instead" \
    "$(printf '%s' "$_woq" | grep -c -- '--staged:')" "0"
# NOT conditional any more. This block used to be wrapped in `if [ -f <workflow> ]`, on the
# rationale that a mutation-test copy contains only scripts/ and unconditional greps would
# drown the signal. That rationale was already false: two sibling assertions further down
# grep the SAME path unguarded, so renaming the workflow reddens the suite regardless
# (measured: 165 passed / 25 failed). The conditional therefore protected nothing while
# silently withdrawing five assertions whenever it fired - a guard that skips itself when
# its target disappears, which is the exact class this whole part exists to eliminate.
# A missing workflow is now a stated FAILURE, not a silent skip.
_wf="$REPO/.github/workflows/secret-scan.yml"
chk "the CI workflow exists (every assertion below reads it)" \
    "$([ -f "$_wf" ] && echo 1 || echo 0)" "1"
if [ -f "$_wf" ]; then
    # EVERY assertion in this block reads CODE ONLY - comments are stripped first via _wfc.
    # An adversarial review found the `--` assertion below matching prose in a comment while
    # its neighbours stripped them, i.e. the block was inconsistent with itself. These stay
    # TEXT assertions over YAML (this is a bash harness; it cannot run a GitHub job), so they
    # prove the SHAPE has not regressed - they are not a substitute for the job running.
    _wfc=$(grep -vE '^[[:space:]]*#' "$_wf")

    # `--` used to sit at end-of-line (`secret-scan.sh --$`) because the arguments arrived
    # from a pipe. They are now passed directly, so anchor on the argument that follows.
    chk "CI passes -- to the scanner" \
        "$(printf '%s\n' "$_wfc" | grep -cE 'secret-scan\.sh -- "')" "1"

    # THE REGRESSION THIS BLOCK EXISTS FOR, and the reason it is a guard rather than a note:
    # the first rewrite of the CI step replaced `| xargs` with `< <(git ls-files -z)` and so
    # traded a COVERAGE guarantee for a diagnosis improvement. `set -euo pipefail` does not
    # cover process substitution - its exit status is structurally unobservable - so with a
    # git that emitted 2 of 3 paths and died (141), the step printed "clean (2 tracked files
    # scanned)" and exited 0 with an unscanned secret in the tree, where the `| xargs` form
    # it replaced went red at 141. Enumeration must go through a FILE whose producer status
    # is checked. This shape has now regressed ONCE, which is the empirical proof that it
    # recurs; hence a machine forbids it rather than a comment asking nicely.
    chk "CI does not enumerate via process substitution (producer status must be checkable)" \
        "$(printf '%s\n' "$_wfc" | grep -cF '< <(')" "0"
    chk "CI checks the enumerator's exit status" \
        "$(printf '%s\n' "$_wfc" | grep -cE 'git ls-files -z > "\$enum"')" "1"
    # A NUL-terminated stream cut off mid-record silently loses its last path to `read -d ''`.
    chk "CI rejects a truncated (non NUL-terminated) enumeration" \
        "$(printf '%s\n' "$_wfc" | grep -c 'no trailing NUL')" "1"

    # The scanner speaks 0 / 2 / 3, and 2 (rotate a live credential) and 3 (the scan could
    # not prove anything) demand opposite responses. Piping it through xargs destroys that:
    # xargs reports its OWN status for any non-zero child - BSD 1, GNU 123 - so both arrive
    # as one indistinguishable red. This is exactly the shape that earns a machine guard:
    # the loss is SILENT (the job is red either way, so nothing looks broken) and the bad
    # shape is the OBVIOUS way to write this step, so it can recur at any time.
    # Comment lines are stripped first - the workflow's own explanation names `| xargs -0`,
    # and a guard that matches its own rationale is a guard that can never fail.
    chk "CI does not pipe the scanner through xargs (rc=2 vs rc=3 must stay distinct)" \
        "$(printf '%s\n' "$_wfc" | grep -cE '\|[[:space:]]*xargs')" "0"

    # An enumeration that yields nothing is a broken enumeration, not a clean tree.
    # Anchored on THIS message, not on the shared "refusing to report clean" phrase: three
    # separate guards now end with that phrase, so counting it asserted 1 and got 3 - a
    # self-inflicted red that reached CI. A guard keyed on a string its own siblings also
    # emit is a guard that breaks every time a sibling is added.
    chk "CI fails closed when no tracked files are enumerated" \
        "$(printf '%s\n' "$_wfc" | grep -c 'enumerated NO tracked files')" "1"

    # Third-party action pinned to an immutable commit, not a tag its publisher can move
    # under us while holding GITHUB_TOKEN. Silent (a moved tag produces no diff here) and
    # recurrent (`@v2` is how everyone writes it), so it gets a guard rather than a note.
    chk "gitleaks action is pinned to a 40-hex commit sha" \
        "$(printf '%s\n' "$_wfc" | grep -cE 'uses: gitleaks/gitleaks-action@[0-9a-f]{40}')" "1"
fi

# ACROSS EVERY WORKFLOW, not just secret-scan.yml. The first version of this guard inspected
# one file, so lint-commands.yml - edited by the very same work that added the guard - was
# covered by nothing. A pinning rule that only watches one of two workflows is a rule an
# unpinned action simply walks around.
# `uses:[[:space:]]+` tolerates the two-space form, which is valid YAML and which a single
# literal space missed entirely. actions/* are GitHub's own first-party actions and are
# exempted by convention; every other publisher must be a 40-hex commit sha.
_wfdir="$REPO/.github/workflows"
if [ -d "$_wfdir" ]; then
    _unpinned=$(cat "$_wfdir"/*.yml 2>/dev/null \
        | grep -vE '^[[:space:]]*#' \
        | grep -E 'uses:[[:space:]]+[^[:space:]]+/' \
        | grep -vE 'uses:[[:space:]]+actions/' \
        | grep -vcE 'uses:[[:space:]]+[^[:space:]]+@[0-9a-f]{40}')
    chk "every non-actions/ third-party action in EVERY workflow is sha-pinned" "$_unpinned" "0"
fi

# 8. --composite mode: primary pattern still fires, path-aware PIN lane does not, and a
#    missing input fails CLOSED rather than inheriting "a missing path is clean".
PINLIT=$(printf '%s%s %s%s' 'P' 'IN:' '4829' '13')
printf '%s\n' "$PINLIT" > pinonly.txt
bash "$SCAN" pinonly.txt >/dev/null 2>&1
chk "PIN lane fires for a normal file scan" "$?" "2"

# 8b. Placeholder suppression must key on the PIN's own VALUE, not on the whole line.
#     Filtering line-wide let a real PIN hide behind an unrelated mention of a placeholder.
PINREAL=$(printf '%s%s%s' 'CRD_' 'PIN=4829' '13')
PINFAKE=$(printf '%s%s' '1234' '56')
printf '%s # changed from %s\n' "$PINREAL" "$PINFAKE" > pinmixed.txt
bash "$SCAN" pinmixed.txt >/dev/null 2>&1
chk "real PIN beside a placeholder mention is caught" "$?" "2"
printf '%s%s\n' 'CRD_PIN=' "$PINFAKE" > pinplaceholder.txt
bash "$SCAN" pinplaceholder.txt >/dev/null 2>&1
chk "a genuine placeholder PIN is still exempt" "$?" "0"
# The harder shape: a real PIN sitting beside a SECOND, labelled placeholder PIN. Both
# earlier filter designs dropped this whole line and let the real value through.
printf '%s %s%s\n' "$PINREAL" 'CRD_PIN=' "$PINFAKE" > pinboth.txt
bash "$SCAN" pinboth.txt >/dev/null 2>&1
chk "real PIN beside a labelled placeholder PIN is caught" "$?" "2"
# Each documented placeholder needs its own case: with only 123456 covered, deleting the
# 000000 exemption left the whole suite green.
printf '%s%s\n' 'CRD_PIN=' '000000' > pinzero.txt
bash "$SCAN" pinzero.txt >/dev/null 2>&1
chk "the 000000 placeholder is exempt" "$?" "0"
# The former "XXXXXX placeholder is exempt" case was DELETED in round 5: RX_PIN requires
# [0-9]{6}, so a letter run is never a candidate in the first place and the case asserted only
# that a non-match is clean. It stayed green when the XXXXXX filter entry was deleted, which is
# how it was caught. The filter entry went with it - it was dead code. A letter run must still
# read as clean, but the honest claim is "never matched", not "exempted":
printf '%s%s\n' 'CRD_PIN=' 'XXXXXX' > pinx.txt
bash "$SCAN" pinx.txt >/dev/null 2>&1
chk "a letter run is not a PIN candidate at all" "$?" "0"
# A six-digit value that is NOT a documented placeholder must still be caught - this is the
# case that gives the two exemption cases above their meaning.
# Digits split across arguments on purpose: written whole, this very line would match RX_PIN
# and turn the repo's own full-tree scan red. It did, on first write.
printf '%s%s%s\n' 'CRD_PIN=' '4829' '13' > pinreal2.txt
bash "$SCAN" pinreal2.txt >/dev/null 2>&1
chk "a non-placeholder six-digit PIN is still caught" "$?" "2"

# 8c. A SYMLINK must be scanned as git stores it - the blob is the target PATH string, not
#     the bytes it points at. Following it both invents false positives on content git never
#     publishes and misses the content git does.
mkdir -p outside_repo; printf '%s\n' "$SECRET" > outside_repo/external-secret
ln -s "$U/outside_repo/external-secret" link-out
bash "$SCAN" link-out >/dev/null 2>&1
chk "a symlink is NOT followed to external content" "$?" "0"
ln -s "$SECRET" link-target-is-secret
bash "$SCAN" link-target-is-secret >/dev/null 2>&1
chk "a symlink whose stored target is a secret is caught" "$?" "2"
# An OPTION-SHAPED link name must still be scanned as a path. Without the `./` guard the name
# reaches readlink as a flag: GNU prints help and exits 0 (link never scanned, reported clean),
# BSD errors out (rc=3). Either way it is not the 2 this must produce. Passed after `--` so the
# leading dash survives argument parsing and actually reaches scan_file.
ln -s "$SECRET" ./-weird-link
bash "$SCAN" -- -weird-link >/dev/null 2>&1
chk "an option-shaped symlink name is still scanned as a path" "$?" "2"
bash "$SCAN" --composite pinonly.txt >/dev/null 2>&1
chk "PIN lane applies in --composite mode too" "$?" "2"
# The allowlist must NOT be consulted for composite input: otherwise a TMPDIR under an
# allowlisted directory silently disables a whole pattern lane.
mkdir -p tmp/briefs; printf '%s\n' "$PINLIT" > tmp/briefs/composite-in.txt
bash "$SCAN" tmp/briefs/composite-in.txt >/dev/null 2>&1
chk "allowlist exempts a PIN at a real allowlisted path" "$?" "0"
bash "$SCAN" --composite tmp/briefs/composite-in.txt >/dev/null 2>&1
chk "allowlist is ignored for --composite input" "$?" "2"
printf '%s\n' "$SECRET" > patchy.txt
bash "$SCAN" --composite patchy.txt >/dev/null 2>&1
chk "--composite still catches a provider token" "$?" "2"
bash "$SCAN" --composite >/dev/null 2>&1
chk "--composite with no file exits 3" "$?" "3"
# The missing-ARGUMENT case above does NOT cover the missing-FILE case: the pre-push hook
# always passes a path, so the reachable failure is the temp file vanishing or being
# unreadable between mktemp and the scan. Reverting that fail-closed branch was undetectable.
_cmsg=$(bash "$SCAN" --composite ./definitely-not-here.txt 2>&1 >/dev/null); _crc=$?
chk "--composite with a MISSING file fails closed (3)" "$_crc" "3"
# The EXIT CODE alone cannot prove this branch exists: with it deleted, a vanished input still
# reaches 3 via the failed redirect, so an rc assertion stays green either way (measured). The
# branch's actual contribution is the specific, actionable diagnostic - so assert THAT. Deleting
# the branch now reddens this line, which is the whole point of having it.
chk "--composite names the missing input explicitly" \
    "$(printf '%s' "$_cmsg" | grep -c 'composite input missing or unreadable')" "1"
printf '%s\n' "$SECRET" > unreadable-composite.txt; chmod 000 unreadable-composite.txt
_umsg=$(bash "$SCAN" --composite unreadable-composite.txt 2>&1 >/dev/null); _urc=$?
chk "--composite with an UNREADABLE file fails closed (3)" "$_urc" "3"
chk "--composite names the unreadable input explicitly" \
    "$(printf '%s' "$_umsg" | grep -c 'composite input missing or unreadable')" "1"
chmod 644 unreadable-composite.txt

# ---------------------------------------------------------------------------
echo "== false-positive gate: the real repository must stay clean =="
# If this ever fails, a regex or filter change made the gate unusable: it would jam every
# commit in this repo AND silently block the async auto-push.
# pipefail matters here: without it a failing `git ls-files` yields empty input and the
# gate passes having scanned nothing at all.
( set -o pipefail; cd "$REPO" && git ls-files -z | xargs -0 bash "$SCAN" -- ) >/dev/null 2>&1
chk "full tree of $(basename "$REPO") scans clean" "$?" "0"
( set -o pipefail; cd "$REPO" && git ls-files -z | wc -c ) >/dev/null 2>&1
chk "full-tree producer itself succeeds" "$?" "0"

# ---------------------------------------------------------------------------
echo "== end-to-end hook cases =="
FIXHOME="$WORK/home"; mkdir -p "$FIXHOME/.claude-dotfiles"
cp -R "$REPO/scripts" "$FIXHOME/.claude-dotfiles/scripts"
# A `commands/` directory is REQUIRED for the fixture to be a faithful stand-in for a real
# checkout: the pre-commit hook this fixture exercises runs lint-skill-size.sh, which now
# fails CLOSED when its ROOT holds no commands/ (a lint that cannot see its tree must not
# report success). Without this the fixture is an incomplete masquerade and every commit in
# it is rejected for the wrong reason - which is exactly what happened when that guard
# landed. The dir is empty on purpose: this suite tests the SECRET gate, not the size lint.
mkdir -p "$FIXHOME/.claude-dotfiles/commands"
R="$FIXHOME/.claude-dotfiles"
git init -q "$R"; git init -q --bare "$WORK/remote.git"
cd "$R" || exit 1
git remote add origin "$WORK/remote.git"
HOME="$FIXHOME" bash "$INSTALL" >/dev/null 2>&1
chk "installer generated pre-push" "$([ -x "$R/.git/hooks/pre-push" ] && echo yes)" "yes"
chk "installer generated pre-commit" "$([ -x "$R/.git/hooks/pre-commit" ] && echo yes)" "yes"
chk "pre-commit keeps secret-scan TERMINAL via exec" \
    "$(grep -cE '^exec .*secret-scan\.sh.* --staged' "$R/.git/hooks/pre-commit")" "1"
# Order is load-bearing: the size lint must run BEFORE the exec, because nothing after an
# exec is reachable. Compare positions rather than a hardcoded line number so a comment
# edit cannot silently turn this assertion into a no-op.
_lint_ln=$(grep -n 'lint-skill-size\.sh' "$R/.git/hooks/pre-commit" | head -1 | cut -d: -f1)
_exec_ln=$(grep -nE '^exec .*secret-scan\.sh' "$R/.git/hooks/pre-commit" | head -1 | cut -d: -f1)
chk "size lint runs BEFORE the terminal exec" \
    "$([ -n "$_lint_ln" ] && [ -n "$_exec_ln" ] && [ "$_lint_ln" -lt "$_exec_ln" ] && echo yes)" "yes"
# Same rule for the contract lint (added 2026-08-02): presence alone is not enough - a line
# that drifts below the exec is unreachable and fails silently open.
_clint_ln=$(grep -n 'lint-skill-contract\.sh' "$R/.git/hooks/pre-commit" | head -1 | cut -d: -f1)
chk "contract lint runs BEFORE the terminal exec" \
    "$([ -n "$_clint_ln" ] && [ -n "$_exec_ln" ] && [ "$_clint_ln" -lt "$_exec_ln" ] && echo yes)" "yes"

BR=$(git symbolic-ref --short HEAD)   # never assume master vs main
rgit() { git --git-dir="$WORK/remote.git" "$@"; }

# A. A clean push must still work. A gate that blocks everything is not a gate.
printf 'hello\n' > a.txt; git add a.txt; HOME="$FIXHOME" git commit -qm clean
HOME="$FIXHOME" git push -q origin "$BR" >/dev/null 2>&1
chk "clean push succeeds" "$?" "0"
BASE=$(rgit rev-parse "$BR" 2>/dev/null)
chk "remote advanced to local HEAD" "$BASE" "$(git rev-parse HEAD)"

# B. The case that justified the whole range design: a secret added and then removed
#    before the tip. The tip tree is clean, so any tip-only scan reports success.
printf '%s\n' "$SECRET" > mid.txt; git add mid.txt
HOME="$FIXHOME" git commit -qm "add cfg" --no-verify >/dev/null
git rm -q mid.txt; HOME="$FIXHOME" git commit -qm "rm cfg" --no-verify >/dev/null
chk "tip tree really is clean" "$(git grep -l "$SECRET" HEAD 2>/dev/null | wc -l | tr -d ' ')" "0"
perr=$(HOME="$FIXHOME" git push origin "$BR" 2>&1); prc=$?
chk "middle-commit secret is rejected" "$([ "$prc" -ne 0 ] && echo yes)" "yes"
chk "rejection shows the scanner banner" "$(printf '%s' "$perr" | grep -c 'BLOCKED: secret detected')" "1"
chk "remote ref did NOT move" "$(rgit rev-parse "$BR")" "$BASE"

# C. A secret that exists only in a commit MESSAGE (no blob anywhere).
# Assert the BANNER, not merely a nonzero exit: `git push` returns 1 for many unrelated
# reasons (bad refspec, no upstream), so a bare rc check can pass without the gate firing.
git reset -q --hard "$BASE"
printf 'ok\n' > c.txt; git add c.txt
HOME="$FIXHOME" git commit -qm "deploy key $SECRET" --no-verify >/dev/null
cerr=$(HOME="$FIXHOME" git push origin "$BR" 2>&1); crc=$?
chk "commit-message secret is rejected" "$([ "$crc" -ne 0 ] && echo yes)" "yes"
chk "message rejection shows the banner" "$(printf '%s' "$cerr" | grep -c 'BLOCKED: secret detected')" "1"
chk "remote ref still did NOT move" "$(rgit rev-parse "$BR")" "$BASE"

# C2. The cleanup case: a commit that REMOVES an already-public secret must still push.
# A raw patch carries deleted and context lines, so scanning them blocks the very commit
# that fixes the leak - the secret can never be removed.
git reset -q --hard "$BASE"
printf '%s\n' "$SECRET" > leaked.txt; git add leaked.txt
HOME="$FIXHOME" git commit -qm "oops" --no-verify >/dev/null
HOME="$FIXHOME" git push -q --no-verify origin "$BR" >/dev/null 2>&1   # simulate: already public
LEAKED=$(rgit rev-parse "$BR")
git rm -q leaked.txt; HOME="$FIXHOME" git commit -qm "remove the leaked file" >/dev/null 2>&1
HOME="$FIXHOME" git push -q origin "$BR" >/dev/null 2>&1
chk "removing an already-public secret still pushes" "$?" "0"
chk "cleanup actually reached the remote" \
    "$([ "$(rgit rev-parse "$BR")" != "$LEAKED" ] && echo moved)" "moved"
git push -q --no-verify origin ":$BR" >/dev/null 2>&1 || true
HOME="$FIXHOME" git reset -q --hard "$BASE"
HOME="$FIXHOME" git push -q --no-verify --force origin "$BR" >/dev/null 2>&1
BASE=$(rgit rev-parse "$BR")

# D. New branch: the old hook diffed against the worktree and enumerated zero files.
git reset -q --hard "$BASE"; git checkout -q -b leakbranch
printf '%s\n' "$SECRET" > n.txt; git add n.txt
HOME="$FIXHOME" git commit -qm new --no-verify >/dev/null
derr=$(HOME="$FIXHOME" git push origin leakbranch 2>&1); drc=$?
chk "new-branch secret is rejected" "$([ "$drc" -ne 0 ] && echo yes)" "yes"
chk "new-branch rejection shows the banner" "$(printf '%s' "$derr" | grep -c 'BLOCKED: secret detected')" "1"
chk "new branch was NOT created on the remote" \
    "$(rgit rev-parse leakbranch >/dev/null 2>&1 && echo present || echo absent)" "absent"

# E. A clean new branch must still push.
git checkout -q -b finebranch "$BASE"
printf 'fine\n' > f.txt; git add f.txt; HOME="$FIXHOME" git commit -qm fine >/dev/null
HOME="$FIXHOME" git push -q origin finebranch >/dev/null 2>&1
chk "clean new branch pushes" "$?" "0"
chk "clean new branch reached the remote" \
    "$(rgit rev-parse finebranch >/dev/null 2>&1 && echo present || echo absent)" "present"

# F. pre-commit must block the staged-index bypass end to end (assert the banner too).
git checkout -q "$BR"
printf '%s\n' "$SECRET" > s.txt; git add s.txt; printf 'harmless\n' > s.txt
ferr=$(HOME="$FIXHOME" git commit -m sneaky 2>&1); frc=$?
chk "pre-commit blocks a staged secret" "$([ "$frc" -ne 0 ] && echo yes)" "yes"
chk "pre-commit rejection shows the banner" "$(printf '%s' "$ferr" | grep -c 'BLOCKED: secret detected')" "1"
git reset -q; rm -f s.txt

# G. TYPE CHANGE: staging a symlink-to-regular-file swap carrying a secret. --diff-filter
#    without T enumerated nothing here and exited 0 - a real bypass of the staged gate.
ln -s /etc/hosts swapme; git add swapme
HOME="$FIXHOME" git commit -qm "add symlink" --no-verify >/dev/null 2>&1
rm swapme; printf '%s\n' "$SECRET" > swapme; git add swapme
# Prove the entry really is status T. If the symlink commit had failed, this would be an
# `A` entry that plain ACMR still scans - the case would pass without testing anything.
chk "the staged entry really is a type change" \
    "$(git diff --cached --name-status --diff-filter=T | awk '{print $1}' | head -1)" "T"
bash "$SCAN" --staged >/dev/null 2>&1
chk "staged symlink-to-file type change is scanned" "$?" "2"
git reset -q --hard HEAD >/dev/null 2>&1

# H. --text must defeat diff suppression. Without it `git log -p` prints "Binary files
#    differ" (or nothing for a `-diff` path) and the pre-push scans no content at all.
printf 'suppressed.txt -diff\n' > .gitattributes
git add .gitattributes; HOME="$FIXHOME" git commit -qm attrs --no-verify >/dev/null 2>&1
printf '%s\n' "$SECRET" > suppressed.txt; git add suppressed.txt
HOME="$FIXHOME" git commit -qm "add suppressed" --no-verify >/dev/null 2>&1
chk "a -diff path really is suppressed in a plain patch" \
    "$(git log -p -1 --no-color | grep -c "$SECRET")" "0"
herr=$(HOME="$FIXHOME" git push origin "$BR" 2>&1)
chk "diff-suppressed secret is still rejected" \
    "$(printf '%s' "$herr" | grep -c 'BLOCKED: secret detected')" "1"
git reset -q --hard "$BASE"

# I. A PIN in a COMMIT MESSAGE must still be caught. The --patch stream deliberately drops
#    the path-aware PIN lane; the message stream must NOT, or this coverage is lost.
PINMSG=$(printf '%s%s %s%s' 'P' 'IN:' '4829' '13')
printf 'x\n' > pm.txt; git add pm.txt
HOME="$FIXHOME" git commit -qm "rotate $PINMSG" --no-verify >/dev/null 2>&1
ierr=$(HOME="$FIXHOME" git push origin "$BR" 2>&1)
chk "PIN in a commit message is rejected" \
    "$(printf '%s' "$ierr" | grep -c 'BLOCKED: secret detected')" "1"
git reset -q --hard "$BASE"

# H2. A textconv diff driver is a LEGITIMATE configuration (readable diffs for binary or
#     noisy files) and it rewrites what `git log -p` prints. Without --no-textconv a driver
#     that scrubs tokens hides the secret completely while git publishes the real blob.
printf 'scrubbed.txt diff=redactor\n' > .gitattributes
git config diff.redactor.textconv "sed s/${_AK}[A-Z0-9]*/SCRUBBED/"
git add .gitattributes; HOME="$FIXHOME" git commit -qm textconv-attrs --no-verify >/dev/null 2>&1
printf '%s\n' "$SECRET" > scrubbed.txt; git add scrubbed.txt
HOME="$FIXHOME" git commit -qm "add scrubbed" --no-verify >/dev/null 2>&1
chk "the textconv driver really does hide it from a plain patch" \
    "$(git log -p --text -1 --no-color | grep -c "$SECRET")" "0"
h2err=$(HOME="$FIXHOME" git push origin "$BR" 2>&1)
chk "textconv-hidden secret is still rejected" \
    "$(printf '%s' "$h2err" | grep -c 'BLOCKED: secret detected')" "1"
git reset -q --hard "$BASE"; git config --unset diff.redactor.textconv 2>/dev/null; rm -f .gitattributes

# I2. A secret in the ROOT commit of a first push. `log.showRoot=false` is an ordinary
#     setting that makes `git log -p` omit the initial commit's patch entirely, so without
#     --root a brand-new repository publishes its root commit unscanned.
ROOTH="$WORK/roothome"; mkdir -p "$ROOTH/.claude-dotfiles"
cp -R "$REPO/scripts" "$ROOTH/.claude-dotfiles/scripts"
RR="$ROOTH/.claude-dotfiles"
git init -q "$RR"; git init -q --bare "$WORK/rootremote.git"
( cd "$RR" && git config log.showRoot false && git remote add origin "$WORK/rootremote.git" )
HOME="$ROOTH" bash "$INSTALL" >/dev/null 2>&1
( cd "$RR" && printf '%s\n' "$SECRET" > r.txt && git add r.txt && \
  HOME="$ROOTH" git commit -qm root --no-verify ) >/dev/null 2>&1
RB=$( cd "$RR" && git symbolic-ref --short HEAD )
( cd "$RR" && HOME="$ROOTH" git push origin "$RB" ) >/dev/null 2>&1
chk "root-commit secret is rejected under log.showRoot=false" \
    "$(git --git-dir="$WORK/rootremote.git" rev-parse "$RB" >/dev/null 2>&1 && echo leaked || echo blocked)" "blocked"

# J. Second remote: tracking refs for remote B must never excuse commits pushed to remote A.
git init -q --bare "$WORK/other.git"
git remote add other "$WORK/other.git"
git checkout -q -b twinbranch "$BASE"
printf '%s\n' "$SECRET" > tw.txt; git add tw.txt
HOME="$FIXHOME" git commit -qm twin --no-verify >/dev/null 2>&1
HOME="$FIXHOME" git push -q --no-verify other twinbranch >/dev/null 2>&1  # now on remote B only
git fetch -q other >/dev/null 2>&1
HOME="$FIXHOME" git push origin twinbranch >/dev/null 2>&1
chk "commits known only to another remote are still scanned" \
    "$(rgit rev-parse twinbranch >/dev/null 2>&1 && echo leaked || echo blocked)" "blocked"
git checkout -q "$BR"; git branch -qD twinbranch >/dev/null 2>&1
git remote remove other >/dev/null 2>&1

# ---------------------------------------------------------------------------
# CONNECTION-STRING + JWT LANES (added 2026-08-03, pd:2-rx-conn-scope resolved "expand properly").
# The DOMINANT risk for these two is FALSE POSITIVES, not misses - a false positive jams every
# commit and silently blocks the async auto-push. So the negative cases below are not padding:
# they are the actual acceptance criteria, and they are what must stay green.
CJ="$WORK/connjwt"; mkdir -p "$CJ"
# Assembled at runtime - a literal JWT or DSN in this tracked file would red the full-tree scan.
_JWT="eyJ$(printf '%s' 'hbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9')"".""eyJ$(printf '%s' 'zdWIiOiIxMjM0NTY3ODkwIn0')"".""$(printf '%s' 'dQw4w9WgXcQabcdefghij')"
printf 'token=%s\n' "$_JWT" > "$CJ/jwt.txt"
bash "$SCAN" "$CJ/jwt.txt" >/dev/null 2>&1
chk "a three-segment JWT is caught" "$?" "2"
# A bare eyJ-prefixed base64 blob is NOT a JWT - only three dot-separated segments are.
printf 'blob=%s\n' "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9" > "$CJ/notjwt.txt"
bash "$SCAN" "$CJ/notjwt.txt" >/dev/null 2>&1
chk "a bare eyJ base64 blob is NOT flagged (prefix alone is not a JWT)" "$?" "0"

_DSN="postgres://admin:$(printf '%s' 's3cr3tpw')@db.example.com:5432/app"
printf 'DATABASE_URL=%s\n' "$_DSN" > "$CJ/dsn.txt"
bash "$SCAN" "$CJ/dsn.txt" >/dev/null 2>&1
chk "a DSN with embedded credentials is caught" "$?" "2"
# NEGATIVE CASES - these are the false positives that would jam every commit in this repo.
printf '%s\n' "postgres://localhost:5432/mydb" > "$CJ/nocred.txt"
bash "$SCAN" "$CJ/nocred.txt" >/dev/null 2>&1
chk "a credential-less DSN is NOT flagged" "$?" "0"
printf '%s\n' "see https://example.com/docs and http://user@host/x" > "$CJ/http.txt"
bash "$SCAN" "$CJ/http.txt" >/dev/null 2>&1
chk "ordinary http(s) URLs are NOT flagged" "$?" "0"
printf 'DB=%s\n' 'postgres://u:${PGPASSWORD}@host/db' > "$CJ/interp.txt"
bash "$SCAN" "$CJ/interp.txt" >/dev/null 2>&1
chk "an INTERPOLATED password is NOT flagged (reference, not a literal)" "$?" "0"
# The repo's own tree is the real regression net for these two lanes.
( cd "$REPO" && git ls-files -z | xargs -0 bash "$SCAN" -- ) >/dev/null 2>&1
chk "full tracked tree stays clean with the new lanes enabled" "$?" "0"

# ---------------------------------------------------------------------------
# INSTALLER CONTENTION. Round 6's unanimous CRITICAL: the installer reported success while
# installing nothing, so dotfiles-sync and SessionStart read "the local gate is fresh" when it
# could be stale or absent. Exercised against a THROWAWAY HOME so the real .git/hooks is never
# touched. Round 5 also deleted age-based lock breaking, so a lock that is never released must
# now produce a LOUD non-zero - never a silent 0.
INST="$REPO/scripts/install-git-hooks.sh"
IH=$(mktemp -d); mkdir -p "$IH/.claude-dotfiles"
cp -R "$REPO/scripts" "$IH/.claude-dotfiles/" 2>/dev/null
( cd "$IH/.claude-dotfiles" && git init -q . 2>/dev/null )
HOME="$IH" bash "$IH/.claude-dotfiles/scripts/install-git-hooks.sh" >/dev/null 2>&1
chk "installer succeeds on a clean tree" "$?" "0"
STAMP_IH="$IH/.claude-dotfiles/.git/hooks/.secret-chain-version"
chk "installer writes a freshness stamp" "$([ -s "$STAMP_IH" ] && echo yes || echo no)" "yes"
# A held lock with a MATCHING stamp is genuinely nothing-to-do -> 0.
mkdir -p "$IH/.claude-dotfiles/.git/hooks/.install.lock"
HOME="$IH" bash "$IH/.claude-dotfiles/scripts/install-git-hooks.sh" >/dev/null 2>&1
chk "contention with a matching stamp is a real no-op (0)" "$?" "0"
# A held lock with NO stamp cannot be verified -> must FAIL LOUD, not report success.
rm -f "$STAMP_IH"
HOME="$IH" bash "$IH/.claude-dotfiles/scripts/install-git-hooks.sh" >/dev/null 2>&1
chk "contention with no verifiable stamp exits 4, not 0" "$?" "4"
rm -rf "$IH"

# PAUSE-MARKER ROUTING. Both readers route on the machine `kind:` field; a wrong branch tells
# the user to clear a leak-caused pause, which resumes pushing to a PUBLIC remote.
NOTICE="$REPO/scripts/hooks/dotfiles-sync-pause-notice.sh"
MK=$(mktemp -d); MKF="$MK/.claude/.dotfiles-sync-paused"; mkdir -p "$MK/.claude"
printf 'kind: secret\nreason: test\n' > "$MKF"
chk "kind=secret notice says ROTATE" \
    "$(HOME="$MK" bash "$NOTICE" 2>&1 | grep -c 'ROTATE')" "1"
printf 'kind: unproven\nreason: test\n' > "$MKF"
# POSITIVE assertions on purpose. The earlier "does NOT say ROTATE" form was decorative:
# deleting the whole `unproven)` arm falls through to `*)`, which also lacks ROTATE, so the
# test stayed green while the branch it names was gone. Assert text unique to the arm.
chk "kind=unproven notice states the range was not PROVEN clean" \
    "$(HOME="$MK" bash "$NOTICE" 2>&1 | grep -c 'could not PROVE the pushed range clean')" "1"
chk "kind=unproven notice directs a push retry, not --working" \
    "$(HOME="$MK" bash "$NOTICE" 2>&1 | grep -c 'RETRYING THE PUSH')" "1"
chk "kind=unproven notice does NOT say ROTATE" \
    "$(HOME="$MK" bash "$NOTICE" 2>&1 | grep -c 'ROTATE')" "0"
# The SECOND reader must know the same vocabulary, or a session-start warning contradicts the
# prompt notice. RUN IT - do not grep it. Rounds 9 and 10 both caught this assertion being
# static: greps for the branch and for the message stayed green even with the `_pkind` reader
# deleted, because the text is still present in the file while the runtime path falls through
# to generic guidance. The guard sources its libs from $HOME/.claude-dotfiles and needs a
# repository cwd, so the fixture HOME symlinks the real tree and the guard runs from $REPO.
GK=$(mktemp -d); mkdir -p "$GK/.claude"; ln -s "$REPO" "$GK/.claude-dotfiles"
printf 'kind: unproven\nreason: test\n' > "$GK/.claude/.dotfiles-sync-paused"
chk "stale-handoff-guard WARNS at runtime on kind=unproven" \
    "$(cd "$REPO" && HOME="$GK" bash "$REPO/scripts/hooks/stale-handoff-guard.sh" 2>&1 | grep -c 'could not PROVE the pushed range clean')" "1"
printf 'kind: secret\nreason: test\n' > "$GK/.claude/.dotfiles-sync-paused"
chk "stale-handoff-guard WARNS at runtime on kind=secret (rotate first)" \
    "$(cd "$REPO" && HOME="$GK" bash "$REPO/scripts/hooks/stale-handoff-guard.sh" 2>&1 | grep -c 'Rotate the credential')" "1"
chk "stale-handoff-guard does NOT say rotate for an unproven pause" \
    "$(printf 'kind: unproven\nreason: t\n' > "$GK/.claude/.dotfiles-sync-paused"; cd "$REPO" && HOME="$GK" bash "$REPO/scripts/hooks/stale-handoff-guard.sh" 2>&1 | grep -c 'Rotate the credential')" "0"
rm -rf "$GK"
printf 'kind: other\nreason: test\n' > "$MKF"
chk "kind=other notice is the plain clear-and-retry form" \
    "$(HOME="$MK" bash "$NOTICE" 2>&1 | grep -c 'Fix the cause above')" "1"
rm -rf "$MK"

# ---------------------------------------------------------------------------
# PART 2 (2026-08-03) - defects found by /god-report and each VERIFIED BY EXECUTION before
# a line of the fix was written. Every case below was watched to FAIL first.

# Under $WORK so it inherits the EXIT/signal trap above. It used to be its own mktemp -d
# with a hand `rm -rf` at the end of the block, which leaked on a signal and gave the file
# two competing temp-dir conventions (round-2 review).
P2W="$WORK/p2"; mkdir -p "$P2W" || { echo "mkdir failed"; exit 1; }

# --- P2: the sk- lane was UNANCHORED, so it matched inside a word: ta|sk-specific...,
# ri|sk-based..., di|sk-space... A false positive here is not cosmetic - it jams every
# commit AND silently halts the async auto-push to the public remote. Measured rc=2 on all
# three of these before the anchor was added.
for _p in 'task-specific-handoff-resolution' 'risk-based-approach-to-secret-scanning' \
          'disk-space-monitoring-and-cleanup-policy'; do
    printf 'A design note about %s in prose.\n' "$_p" > "$P2W/prose.md"
    bash "$SCAN" "$P2W/prose.md" >/dev/null 2>&1
    chk "ordinary prose containing '${_p%%-*}-' is not a secret" "$?" "0"
done

# Regression guard for the anchor: a REAL sk- key must STILL be caught. Without this the
# "fix" could be a deletion of the lane and the suite would stay green.
printf 'key=%s%s\n' 'sk-' "$(printf 'A%.0s' $(seq 40))" > "$P2W/realkey.txt"
bash "$SCAN" "$P2W/realkey.txt" >/dev/null 2>&1
chk "a real sk- key is still caught after anchoring" "$?" "2"

# --- P2 REVIEW FIX: the boundary must exclude ONLY alphanumerics. The first draft used
# [^A-Za-z0-9_-], which treats _ and - as part of the preceding word and so MISSED a real
# key glued to a separator - trading a false positive for a false NEGATIVE on the one
# control between this repo and a public remote. Caught by 3 of 4 Codex lenses.
for _sep in '_' '-'; do
    printf 'token=backup%s%s%s\n' "$_sep" 'sk-' "$(printf 'D%.0s' $(seq 40))" > "$P2W/glued.txt"
    bash "$SCAN" "$P2W/glued.txt" >/dev/null 2>&1
    chk "a real key glued to a '$_sep' separator is still CAUGHT" "$?" "2"
done

# --- P3: an unrecognized flag fell through the mode `case` to the path branch, became a
# nonexistent filename, was skipped, and the scanner exited 0 having scanned NOTHING.
# Most consumers render no human-facing prose, so none of them would notice.
bash "$SCAN" --no-such-flag >/dev/null 2>&1
chk "unknown flag is rejected, not treated as a filename" "$?" "3"
bash "$SCAN" --stdin >/dev/null 2>&1
chk "unknown flag --stdin is rejected (there is no stdin mode)" "$?" "3"
# P3 REVIEW FIX: the first draft matched `--*` only, so SINGLE-dash options still fell
# through and exited 0 having scanned nothing. `-staged` is the most likely typo of the
# flag the pre-commit hook actually passes. Caught by all 4 Codex lenses.
for _bad in -staged -x -working; do
    bash "$SCAN" "$_bad" >/dev/null 2>&1
    chk "single-dash '$_bad' is rejected, not silently skipped" "$?" "3"
done
# A real file whose name begins with a dash must STILL be reachable via the `--` sentinel,
# so the widened rejection cannot have broken the documented escape hatch.
printf 'nothing to see\n' > "$P2W/-dashfile.txt"
( cd "$P2W" && bash "$SCAN" -- "-dashfile.txt" >/dev/null 2>&1 )
chk "a dash-leading PATH is still scannable after -- (clean file)" "$?" "0"

# --- P1b: npm auth tokens had no lane at all, so an .npmrc sailed through the scanner.
printf '//registry.npmjs.org/:_authToken=%s%s\n' 'npm_' "$(printf 'B%.0s' $(seq 36))" \
    > "$P2W/npmrc.txt"
bash "$SCAN" "$P2W/npmrc.txt" >/dev/null 2>&1
chk "an npm auth token is caught" "$?" "2"
rm -rf "$P2W"

# --- P1a: secret-bearing filenames MUST be gitignored. This repo runs `git add -A` and
# auto-pushes to a PUBLIC remote. Note the asymmetry that makes this the load-bearing
# layer: an arbitrary `export DB_PASSWORD=<opaque>` in .envrc is uncatchable by ANY
# scanner, so for that file gitignore is the ONLY control that can work.
for _f in .envrc .npmrc .dockercfg credentials.json .netrc .docker/config.json; do
    ( cd "$REPO" && git check-ignore -q "$_f" )
    chk "$_f is gitignored" "$?" "0"
done
# REVIEW FIX: a gitignore pattern containing a slash is ROOT-ANCHORED. The first draft wrote
# `.docker/config.json`, which does not match at depth - and it was the one new entry the
# loop above originally omitted, so the gap was untested. These assert depth-matching for
# every new entry, which is what the sibling slash-free patterns already give for free.
for _f in sub/.envrc deep/nested/.npmrc sub/.docker/config.json; do
    ( cd "$REPO" && git check-ignore -q "$_f" )
    chk "$_f is gitignored at depth" "$?" "0"
done

# --- P6: settings.json.template inlined a SECOND copy of RX for its SessionStart scan of
# ~/.config/claude/credentials.md. It had already diverged - missing the JWT and
# connection-string lanes - so a JWT there was never warned about while the same value in
# a repo file was caught. The fix is single-source: call the real scanner, do not sync two
# copies. These assert the duplicate is GONE, not that it matches.
chk "template no longer inlines a second copy of RX" \
    "$(grep -c 'AKIA\[0-9A-Z\]' "$REPO/settings.json.template")" "0"
chk "template credentials scan calls the canonical scanner" \
    "$(grep -q 'secret-scan.sh' "$REPO/settings.json.template" && echo yes || echo no)" "yes"

# ---------------------------------------------------------------------------
echo
echo "== PART 3: round-2 review fixes (every case measured 2026-08-03) =="
P3W="$WORK/p3"; mkdir -p "$P3W"

# --- R2-CRITICAL: NUL must be TRANSLATED, never deleted. `tr -d "\000"` closed the gap
# between the bytes around a NUL, so `X\0sk-<key>` collapsed to `Xsk-<key>` and the
# round-1 boundary anchor `(^|[^A-Za-z0-9])` had nothing to match. MEASURED rc=0 before
# the fix, rc=2 after, on identical bytes. This is a false NEGATIVE the anchoring fix
# itself introduced - the unanchored regex it replaced caught this case.
python3 - "$P3W/nul-sep.bin" <<'PYEOF'
import sys
open(sys.argv[1], 'wb').write(b'X\x00' + ('sk-' + 'A' * 44).encode() + b'\n')
PYEOF
bash "$SCAN" "$P3W/nul-sep.bin" >/dev/null 2>&1
chk "a NUL byte before a token does not hide it (boundary survives)" "$?" "2"

# Line numbering must survive the translation - a newline substitute would renumber every
# reported hit in a NUL-bearing file, making the hit output point at the wrong line.
python3 - "$P3W/nul-multi.bin" <<'PYEOF'
import sys
open(sys.argv[1], 'wb').write(b'line1\nline2 has\x00' + ('sk-' + 'A' * 44).encode() + b'\nline3\n')
PYEOF
chk "NUL translation preserves line numbers in the hit output" \
    "$(bash "$SCAN" "$P3W/nul-multi.bin" 2>&1 | grep -oE 'nul-multi\.bin:[0-9]+' | head -1)" \
    "nul-multi.bin:2"

# --- R2: an EXPLICIT-PATH invocation that scanned zero files must never report clean.
# Each of these was a SEPARATE route to "scanned nothing, exited 0"; all MEASURED rc=0
# before the fix. The counter asserts the invariant rather than enumerating the routes.
printf 'nothing to see here\n' > "$P3W/ok.txt"
bash "$SCAN" -- >/dev/null 2>&1
chk "-- with no paths refuses to report clean" "$?" "3"
bash "$SCAN" /no/such/file >/dev/null 2>&1
chk "a nonexistent EXPLICIT path is rc=3, not rc=0" "$?" "3"
bash "$SCAN" "$P3W/ok.txt" --stdin >/dev/null 2>&1
chk "an unknown option in NON-first position is rejected" "$?" "3"
bash "$SCAN" "$P3W/ok.txt" -staged >/dev/null 2>&1
chk "a single-dash typo in non-first position is rejected" "$?" "3"
# A directory cannot be scanned, so it cannot be pronounced clean either.
bash "$SCAN" "$P3W" >/dev/null 2>&1
chk "a directory argument is rc=3, not rc=0" "$?" "3"
# ...while the legitimate shapes must all still work.
bash "$SCAN" "$P3W/ok.txt" >/dev/null 2>&1
chk "a real clean file is still rc=0" "$?" "0"
bash "$SCAN" -- "$P3W/ok.txt" >/dev/null 2>&1
chk "-- followed by a real clean path is still rc=0" "$?" "0"

# --- R2: the .aws pair was the SAME root-anchoring defect the .gitignore comment
# documents, three lines above it. MEASURED NOT-IGNORED at depth before the fix.
# .aws/config is the sharper case: it carries no AKIA-shaped token, so the scanner lane
# offered as the alternate cover does not fire either - both layers assumed the other.
for _f in .aws/credentials .aws/config .git-credentials; do
    ( cd "$REPO" && git check-ignore -q "$_f" )
    chk "$_f is gitignored" "$?" "0"
done
# Depth coverage for EVERY ignore entry this chain relies on. The round-1 loop covered
# only three of them, so the two it omitted could have become root-anchored unnoticed.
for _f in sub/.aws/credentials deep/x/.aws/config sub/.git-credentials \
          sub/.dockercfg sub/credentials.json sub/.netrc; do
    ( cd "$REPO" && git check-ignore -q "$_f" )
    chk "$_f is gitignored at depth" "$?" "0"
done

# --- R2: the rc=2 / rc=3 split in the SessionStart consumer had ZERO regression net -
# reverting it left the suite 116/0 green (proved by mutation). It is the only consumer
# that renders the exit code as prose a human reads, so collapsing "scan failed" into
# "rotate your credential" cries wolf. Assert the BEHAVIOUR, not the source text.
# Extract ONLY the credentials-scan segment. The full hook command begins with
# `cd ~/.claude-dotfiles && git pull ... && install-git-hooks.sh`, so running it whole
# under a fake HOME measures the scanner PATH failing to resolve, not the scan logic
# (that mistake made this very test report a warning on a clean catalog). The scanner
# path is rewritten to the real one so HOME only redirects the catalog location.
_tmpl_cmd=$(python3 - "$REPO/settings.json.template" "$SCAN" <<'PYEOF'
import json, sys, re
raw = open(sys.argv[1]).read()
raw = re.sub(r'^\s*//.*$', '', raw, flags=re.M)
cfg = json.loads(raw)
for grp in cfg.get('hooks', {}).get('SessionStart', []):
    for h in grp.get('hooks', []):
        c = h.get('command', '')
        # Anchored on the start of the credentials segment (the symlink-resolution
        # assignment), NOT on the `if [ -f ... ]` that used to open it - changing the
        # command shape must not silently make this extractor find nothing and skip.
        i = c.find('C=~/.config/claude/credentials.md')
        if i != -1:
            seg = c[i:]
            seg = seg.replace('"$HOME/.claude-dotfiles/scripts/secret-scan.sh"', '"%s"' % sys.argv[2])
            seg = seg.replace('~/.claude-dotfiles/scripts/secret-scan.sh', sys.argv[2])
            print(seg)
            sys.exit(0)
sys.exit(1)
PYEOF
) || _tmpl_cmd=""
if [ -n "$_tmpl_cmd" ]; then
    _FH="$P3W/fakehome"; mkdir -p "$_FH/.config/claude"
    # clean catalog -> silent
    printf 'OPENAI_API_KEY  op://Personal/openai/key\n' > "$_FH/.config/claude/credentials.md"
    chk "template hook: clean catalog says nothing" \
        "$(HOME="$_FH" bash -c "$_tmpl_cmd" 2>&1 | grep -c 'WARNING')" "0"
    # real secret -> tells the human to ROTATE
    printf 'k=sk-%s\n' "$(python3 -c "print('A'*44)")" >> "$_FH/.config/claude/credentials.md"
    chk "template hook: a real secret warns" \
        "$(HOME="$_FH" bash -c "$_tmpl_cmd" 2>&1 | grep -ci 'possible secret')" "1"
    # A SYMLINKED catalog must still be scanned by CONTENT. `[ -f ]` follows the link, but
    # scan_file deliberately reads a symlink's stored TARGET PATH (that string is what git
    # publishes) - correct for the git consumers, silently wrong for this one, which scans a
    # file outside any repo. MEASURED before the fix: a symlink to a secret-bearing catalog
    # returned rc=0 while the target itself returned rc=2. The consumer now resolves first.
    _SL="$P3W/slhome"; mkdir -p "$_SL/.config/claude" "$_SL/real"
    printf 'k=sk-%s\n' "$(python3 -c "print('A'*44)")" > "$_SL/real/actual-credentials.md"
    ln -sf "$_SL/real/actual-credentials.md" "$_SL/.config/claude/credentials.md"
    chk "template hook: a SYMLINKED catalog is scanned by content, not by link target" \
        "$(HOME="$_SL" bash -c "$_tmpl_cmd" 2>&1 | grep -ci 'possible secret')" "1"

    # unreadable catalog -> a SCAN FAILURE, and must NOT say rotate
    chmod 000 "$_FH/.config/claude/credentials.md" 2>/dev/null
    _out=$(HOME="$_FH" bash -c "$_tmpl_cmd" 2>&1)
    chmod 644 "$_FH/.config/claude/credentials.md" 2>/dev/null
    if [ "$(id -u)" -eq 0 ]; then
        # root ignores the mode bits, so the unreadable case cannot be staged. Skip
        # honestly rather than assert something the environment cannot produce.
        chk "template hook: scan failure is distinguished from a hit (SKIPPED as root)" "skip" "skip"
    else
        # The message legitimately CONTAINS the word "rotate" - as "Do not rotate anything".
        # Asserting absence of the bare word matched that and failed; the property is that
        # it must not issue the ROTATE IMPERATIVE the rc=2 branch issues.
        chk "template hook: scan failure does NOT tell the human to rotate" \
            "$(printf '%s' "$_out" | grep -ci 'Rotate the leaked secret')" "0"
        chk "template hook: scan failure explicitly says do NOT rotate" \
            "$(printf '%s' "$_out" | grep -ci 'Do not rotate')" "1"
        chk "template hook: scan failure is reported as a scan failure" \
            "$(printf '%s' "$_out" | grep -ci 'SCAN FAILURE')" "1"
    fi
else
    chk "template hook command was extractable from settings.json.template" "no" "yes"
fi

# --- R2: pre-push executed the scanner directly while guarding only readability, so a
# lost executable bit produced rc=126 - outside the 0/2/3 vocabulary - and the
# RANGE-NOT-PROVEN-CLEAN token every consumer greps for was never printed.
chk "pre-push invokes the scanner via bash (exec bit cannot break the contract)" \
    "$(grep -c 'bash "\$SCAN" --composite' "$INSTALL")" "1"
chk "pre-push normalizes an out-of-contract rc to 3" \
    "$(grep -c 'treating as could-not-scan' "$INSTALL")" "1"

# ===========================================================================
echo
echo "== PART 4: round-3 review fixes (every case measured 2026-08-03) =="
P4W="$WORK/p4"; mkdir -p "$P4W"

# --- R3-CRITICAL: --working was the ONLY mode branch that never assigned MODE, so it ran as
# MODE=file and inherited the explicit-path zero-scanned invariant: a CLEAN working tree
# returned rc=3. dotfiles-sync.sh (the sole --working consumer) maps any non-0/2 to a
# `kind: unproven` pause marker that halts ALL future auto-sync - so this would have jammed
# the auto-push permanently, behind a false "could not prove the working tree clean".
# This shipped green because ZERO of the previous 144 cases invoked --working at all: the one
# mode the public auto-push depends on was the one mode with no coverage.
_wt="$P4W/wt"; mkdir -p "$_wt"
( cd "$_wt" && git init -q . && git config user.email t@t.invalid && git config user.name t \
  && printf 'hello\n' > a.txt && git add a.txt && git commit -qm init ) >/dev/null 2>&1
( cd "$_wt" && bash "$SCAN" --working >/dev/null 2>&1 )
chk "--working on a CLEAN tree is rc=0 (never jams the auto-push)" "$?" "0"
( cd "$_wt" && git rm -q a.txt && bash "$SCAN" --working >/dev/null 2>&1 )
chk "--working on a DELETION-ONLY change is rc=0" "$?" "0"
( cd "$_wt" && git reset -q --hard >/dev/null 2>&1
  printf 'k=sk-%s\n' "$(python3 -c "print('A'*44)")" > leak.txt
  bash "$SCAN" --working >/dev/null 2>&1 )
chk "--working still CATCHES an untracked secret (rc=2)" "$?" "2"
( cd "$_wt" && rm -f leak.txt
  printf 'k=sk-%s\n' "$(python3 -c "print('A'*44)")" > tracked.txt
  git add tracked.txt >/dev/null 2>&1
  bash "$SCAN" --working >/dev/null 2>&1 )
chk "--working catches a secret in a MODIFIED tracked file (rc=2)" "$?" "2"
( cd "$_wt" && git reset -q --hard >/dev/null 2>&1; rm -f tracked.txt )

# --- R3: the enumerate-everything modes silently DISCARDED extra arguments. `--staged <path>`
# exited 0 having scanned the index while the caller believed it scanned that path.
( cd "$_wt" && bash "$SCAN" --staged --bogus >/dev/null 2>&1 )
chk "--staged rejects an extra unknown flag instead of ignoring it" "$?" "3"
( cd "$_wt" && bash "$SCAN" --staged some-path.txt >/dev/null 2>&1 )
chk "--staged rejects a stray PATH instead of silently scanning the index" "$?" "3"
( cd "$_wt" && bash "$SCAN" --working extra >/dev/null 2>&1 )
chk "--working rejects an extra argument" "$?" "3"

# --- R3: a non-regular entry must NOT be rc=3. `git ls-files` emits submodule GITLINK paths,
# which are directories on disk; failing on them would turn the CI full-tree scan permanently
# red the day a submodule is added - and a gate that reddens on a legitimate repo shape gets
# switched off by a human. It must still not count as scanned (see the lone-directory case).
mkdir -p "$P4W/adir"
printf 'nothing\n' > "$P4W/plain.txt"
bash "$SCAN" "$P4W/plain.txt" "$P4W/adir" >/dev/null 2>&1
chk "a directory ALONGSIDE a real file does not fail the batch" "$?" "0"
bash "$SCAN" "$P4W/adir" >/dev/null 2>&1
chk "a directory ALONE is rc=3 (nothing was actually scanned)" "$?" "3"

# --- R3: the pre-push assertions were grep-only and PROVEN HOLLOW - the rc-normalization
# could be moved to where it no longer works and the suite stayed 144/0 green. Assert the
# BEHAVIOUR: with a scanner that returns an out-of-contract rc, the hook must still emit the
# RANGE-NOT-PROVEN-CLEAN token that dotfiles-sync greps for, and must still fail closed.
# A REAL push against a REAL bare remote, with the scanner replaced by a stub returning an
# out-of-contract rc. Hand-driving the hook body does not work (the hook assigns SCAN itself
# and reads its ref list from stdin), and grep-only assertions are exactly what proved hollow.
# The HOME override is what makes the generated hook resolve to the stub.
_PPH="$P4W/pphome"; mkdir -p "$_PPH/.claude-dotfiles"
cp -R "$REPO/scripts" "$_PPH/.claude-dotfiles/scripts"
_PPR="$_PPH/.claude-dotfiles"
git init -q "$_PPR"; git init -q --bare "$P4W/ppremote.git"
( cd "$_PPR" && git remote add origin "$P4W/ppremote.git" && HOME="$_PPH" bash "$INSTALL" ) >/dev/null 2>&1
# Out-of-contract rc: neither 0, 2, nor 3. Pre-round-3 this exited carrying 126 and the token
# every consumer greps for was never printed, so a could-not-scan was filed as a routine failure.
printf '#!/bin/bash\nexit 126\n' > "$_PPR/scripts/secret-scan.sh"
chmod +x "$_PPR/scripts/secret-scan.sh"
_ppbr=$( cd "$_PPR" && git symbolic-ref --short HEAD )
_ppout=$( cd "$_PPR" && printf 'x\n' > f.txt && git add f.txt \
          && HOME="$_PPH" git -c core.hooksPath=.git/hooks commit -qm t --no-verify \
          && HOME="$_PPH" git push origin "$_ppbr" 2>&1 )
_pprc=$?
chk "pre-push FAILS CLOSED on an out-of-contract scanner rc" \
    "$([ "$_pprc" -ne 0 ] && echo blocked || echo allowed)" "blocked"
chk "pre-push still emits RANGE-NOT-PROVEN-CLEAN for an out-of-contract rc" \
    "$(printf '%s' "$_ppout" | grep -c 'RANGE-NOT-PROVEN-CLEAN' | tr -d ' ')" "1"

# --- R3: the anti-drift guard grepped ONE literal in TWO directories, so it reported green
# while a stale count sat in scripts/dotfiles-sync.sh - a file inside its own search path,
# with different wording. Widened to the whole repo, but the phrasings are tied to THIS
# subject: the first widening matched commands/implement.md's ordinary English ("three of the
# four outcomes are serial"), a false positive. A guard that cries wolf on unrelated prose
# gets deleted by the next person, so it must name consumers/layers explicitly.
# THE GUARD NOW CHECKS THE PROPERTY, NOT THE PREVIOUS WORDING. The old versions were a
# blocklist of the LAST round's numeral, so each time the count drifted forward they passed
# while a stale count sat in the repo - a guard reporting success on a target it structurally
# could not see, which is this mission's governing bug class inside the proof suite itself.
# It drifted three times that way ("three of four" -> "FIVE" -> "SIX"). The numerals are now
# DELETED from the source; this asserts that no NEW one appears, in any spelling.
# Two shapes, because the first draft of this guard matched neither "SIX consumers." nor
# "All six branch on the exit code" - it was mutation-tested and stayed GREEN, i.e. it was
# itself a guard that could not reach its target. Widened and re-mutated until it goes red:
#   (1) a number immediately qualifying consumers/layers  ("six consumers", "5 layers")
#   (2) "all <number>" / "of the <number>"                 ("All six branch", "of the four")
# SCOPED TO THE FILES THAT DESCRIBE THIS CHAIN, deliberately. A repo-wide version matched
# ordinary unrelated English ("Two layers" in the macmini skill, in pre-compact's wrong-load
# defense) - 84 files on the first attempt, 12 on the second. A guard that cries wolf gets
# deleted by the next person, so it is aimed where the invariant actually lives. Mutation-
# tested in both directions: it goes RED when a numeral is reintroduced, and GREEN on the
# unrelated prose elsewhere in the repo.
_n='(one|two|three|four|five|six|seven|eight|nine|ten|[0-9]+)'
# An ARRAY, and grep's own status is checked. The first draft used an unquoted scalar, so a
# checkout path containing a space would split every target into nonexistent arguments,
# suppress the errors with 2>/dev/null, count 0 and report PASS having scanned nothing - the
# governing bug class, in the guard written to enforce it. Now: missing target => loud FAIL.
_chainfiles=( "$REPO/scripts/secret-scan.sh" "$REPO/scripts/dotfiles-sync.sh" "$REPO/docs/SECURITY-secret-chain.md" )
_missing=0
for _cf in "${_chainfiles[@]}"; do [ -r "$_cf" ] || _missing=$((_missing + 1)); done
chk "the count guard can actually reach all of its target files" "$_missing" "0"
# grep's OWN STATUS is captured, not just its line count. `grep | wc | tr` discards it, so a
# regex error or an unreadable target yielded 0 matches -> "0" -> PASS, the guard reporting
# success without having evaluated anything (three reviewers, and the comment above used to
# claim the status WAS checked while it was not). grep: 0=match 1=no-match >1=error.
_gout=$(grep -ilE "(^|[^A-Za-z])${_n}[[:space:]]+(consumers|layers)|(all|of the)[[:space:]]+${_n}[[:space:]]+(consumers|layers|branch|share|call)" \
          "${_chainfiles[@]}" 2>/dev/null); _grc=$?
chk "the count guard's grep ran without error (rc 0 or 1, never >1)" \
    "$([ "$_grc" -le 1 ] && echo ok || echo "error-rc=$_grc")" "ok"
chk "no numeric consumer/layer count in the chain's own files (the numeral drifted 3x)" \
    "$(printf '%s' "$_gout" | grep -c . | tr -d ' ')" "0"

# --- R3: this entry shipped with NO assertion at all, at any depth.
for _f in .config/git/credentials sub/git/credentials; do
    ( cd "$REPO" && git check-ignore -q "$_f" )
    chk "$_f is gitignored" "$?" "0"
done

# ===========================================================================
echo
echo "== PART 5: round-4 review fixes (every case measured 2026-08-03) =="
P5W="$WORK/p5"; mkdir -p "$P5W"

# --- R4-CRITICAL: --working enumerates REPO-ROOT-RELATIVE paths but used to resolve them
# against the CALLER's cwd, so from any subdirectory every path missed and the mode - which
# round 3 had exempted from the zero-scanned invariant - returned rc=0 CLEAN on a tree
# holding a real key. Round 3 closed a false positive and opened a false negative.
# It was reachable by a HUMAN: dotfiles-sync-pause-notice.sh names this exact command as the
# "Confirm clean" gate before deleting a leak marker and resuming PUBLIC pushes.
_r4="$P5W/wt"; mkdir -p "$_r4/deep/nest"
( cd "$_r4" && git init -q . && git config user.email t@t.invalid && git config user.name t \
  && printf 'x\n' > deep/nest/a.txt && git add -A && git commit -qm init ) >/dev/null 2>&1
printf 'k=sk-%s\n' "$(python3 -c "print('A'*44)")" > "$_r4/deep/nest/a.txt"
for _d in "" "deep" "deep/nest"; do
    ( cd "$_r4/$_d" && bash "$SCAN" --working >/dev/null 2>&1 )
    chk "--working catches a secret from subdir '${_d:-<root>}'" "$?" "2"
done
# The round-3 tolerances must survive the round-4 fix.
( cd "$_r4" && git checkout -q -- deep/nest/a.txt && bash "$SCAN" --working >/dev/null 2>&1 )
chk "--working clean tree still rc=0 after the cwd fix" "$?" "0"
( cd "$_r4" && git rm -q deep/nest/a.txt && bash "$SCAN" --working >/dev/null 2>&1 )
chk "--working deletion-only still rc=0 after the cwd fix" "$?" "0"
( cd "$_r4" && git reset -q --hard ) >/dev/null 2>&1

# --- R4: a staged SUBMODULE GITLINK made pre-commit rc=3, refusing the commit permanently
# and turning into a pause marker that halts auto-sync. `git cat-file -t ":<gitlink>"` exits
# 128 instead of printing a type, so the `[ "$t" = blob ] || continue` guard written for
# this case was unreachable dead code. Gitlinks are now detected by index MODE (160000).
_sub="$P5W/sub"; _main="$P5W/main"
( git init -q "$_sub" && cd "$_sub" && git config user.email t@t.invalid && git config user.name t \
  && printf 'x\n' > f.txt && git add f.txt && git commit -qm s1 ) >/dev/null 2>&1
( git init -q "$_main" && cd "$_main" && git config user.email t@t.invalid && git config user.name t \
  && printf 'base\n' > base.txt && git add base.txt && git commit -qm init ) >/dev/null 2>&1
_subsha=$( cd "$_sub" && git rev-parse HEAD )
( cd "$_main" && mkdir -p mod && git update-index --add --cacheinfo "160000,$_subsha,mod" ) >/dev/null 2>&1
chk "fixture really staged a gitlink (mode 160000)" \
    "$(cd "$_main" && git ls-files -s -- mod | awk '{print $1}')" "160000"
( cd "$_main" && bash "$SCAN" --staged >/dev/null 2>&1 )
chk "--staged tolerates a submodule gitlink (never jams the commit gate)" "$?" "0"
# ...and a real staged secret alongside the gitlink must STILL be caught.
( cd "$_main" && printf 'k=sk-%s\n' "$(python3 -c "print('A'*44)")" > s.txt && git add s.txt \
  && bash "$SCAN" --staged >/dev/null 2>&1 )
chk "--staged still catches a secret staged alongside a gitlink" "$?" "2"

# --- R4: the "enumerated something but reached none of it" invariant. Round 2 scoped the
# zero-scanned check to explicit-path mode, which is what let the --working cwd bug be
# silent. It now applies in EVERY mode - while a clean tree, which enumerates nothing, is
# untouched (that distinction is the whole reason deletions are excluded at enumeration).
chk "a lone unreachable explicit path is still rc=3" \
    "$(bash "$SCAN" /no/such/file >/dev/null 2>&1; echo $?)" "3"

# --- R4: the suite closes stdin at source. Round 3 patched only the CI call site, leaving
# every other caller able to hang forever on stale-handoff-guard's `HOOK_JSON=$(cat)`.
chk "the suite closes its own stdin (hang cannot recur for any caller)" \
    "$(grep -c '^exec </dev/null' "$REPO/scripts/hooks/test-secret-scan.sh")" "1"

# --- R4: dotfiles-sync was the consumer round 3's exec-bit class fix missed. Proven
# load-bearing by execution: without the `bash` prefix a lost exec bit gives 126 -> an
# `unproven` marker -> all auto-sync halted.
chk "dotfiles-sync invokes the scanner via bash (exec bit cannot jam auto-sync)" \
    "$(grep -c 'bash "\$DOTFILES_DIR/scripts/secret-scan.sh" --working' "$REPO/scripts/dotfiles-sync.sh")" "1"

# --- R4: the CI step must keep BOTH the stdin redirect and a timeout. A hung job is neither
# green nor red - the governing bug class one level up.
chk "CI runs the suite with </dev/null" \
    "$(grep -c 'test-secret-scan.sh </dev/null' "$REPO/.github/workflows/secret-scan.yml")" "1"
# Matches the YAML KEY, not the word: the first draft counted its own explanatory comment
# too and reported 2. An assertion that can match prose about itself is not an assertion.
chk "CI bounds the suite with timeout-minutes" \
    "$(grep -cE '^[[:space:]]*timeout-minutes:' "$REPO/.github/workflows/secret-scan.yml")" "1"

# --- R4: the SessionStart symlink loop must report a scan FAILURE past its hop limit rather
# than falling through and scanning the link path (silent clean on a real secret).
chk "SessionStart reports a scan failure past the symlink hop limit" \
    "$(grep -c 'symlink chain deeper than 10 hops' "$REPO/settings.json.template")" "1"

# --- R4: the god-review 2.4 block is another scanner consumer; it must propagate the
# status rather than exiting 0 while printing FINDINGS, and must not accept an unset WORKDIR.
chk "2.4 scan block propagates the scanner exit code" \
    "$(grep -c '^exit \$rc' "$REPO/commands/god-review/principles/secret-leak.md")" "1"
chk "2.4 scan block refuses an unset WORKDIR" \
    "$(grep -c 'WORKDIR is unset' "$REPO/commands/god-review/principles/secret-leak.md")" "1"

# ===========================================================================
echo
echo "== PART 6: round-5 review fixes (every case measured 2026-08-03) =="
P6W="$WORK/p6"; mkdir -p "$P6W"

# --- R5-CRITICAL: --working returned rc=3 whenever EVERY enumerated path was non-regular,
# which dotfiles-sync turns into a permanent pause marker halting all auto-push. Round 4
# widened the "enumerated but reached none" invariant to every mode while leaving this
# branch's round-3 "not counted as scanned" skip in place; the two contradicted each other.
# All three shapes below are ORDINARY, not exotic - (a) is any agent running `git init` in a
# scratch directory.
_r5="$P6W/wt"; mkdir -p "$_r5"
( cd "$_r5" && git init -q . && git config user.email t@t.invalid && git config user.name t \
  && printf 'base\n' > base.txt && git add base.txt && git commit -qm init ) >/dev/null 2>&1
# (a) an untracked NESTED REPO is the only change
( cd "$_r5" && mkdir -p nested && cd nested && git init -q . ) >/dev/null 2>&1
( cd "$_r5" && bash "$SCAN" --working >/dev/null 2>&1 )
chk "--working tolerates an untracked nested repo (no auto-push jam)" "$?" "0"
rm -rf "$_r5/nested"
# (b) a submodule GITLINK bump is the only change
_r5sub="$P6W/sub"
( git init -q "$_r5sub" && cd "$_r5sub" && git config user.email t@t.invalid && git config user.name t \
  && printf 'x\n' > f && git add f && git commit -qm s1 ) >/dev/null 2>&1
( cd "$_r5" && mkdir -p modx \
  && git update-index --add --cacheinfo "160000,$(git -C "$_r5sub" rev-parse HEAD),modx" \
  && git commit -qm addsub ) >/dev/null 2>&1
( cd "$_r5sub" && printf 'y\n' >> f && git commit -qam s2 ) >/dev/null 2>&1
( cd "$_r5" && git update-index --cacheinfo "160000,$(git -C "$_r5sub" rev-parse HEAD),modx" ) >/dev/null 2>&1
( cd "$_r5" && bash "$SCAN" --working >/dev/null 2>&1 )
chk "--working tolerates a submodule gitlink bump alone (no auto-push jam)" "$?" "0"
( cd "$_r5" && git reset -q --hard ) >/dev/null 2>&1
# ...and the tolerance must NOT have blinded it: a real secret alongside is still caught.
( cd "$_r5" && mkdir -p nested2 && cd nested2 && git init -q . ) >/dev/null 2>&1
printf 'k=sk-%s\n' "$(python3 -c "print('A'*44)")" > "$_r5/leak.txt"
( cd "$_r5" && bash "$SCAN" --working >/dev/null 2>&1 )
chk "--working still catches a secret beside a nested repo" "$?" "2"
rm -rf "$_r5/nested2" "$_r5/leak.txt"

# --- R5: an EXPLICIT-PATH caller must keep the opposite accounting - a lone directory is
# NOT accounted for, so it still trips the invariant. The two intents differ by who chose
# the path, which is exactly the distinction round 4 collapsed.
mkdir -p "$P6W/adir"
bash "$SCAN" "$P6W/adir" >/dev/null 2>&1
chk "a lone directory ARGUMENT is still rc=3 (caller asked, nothing scanned)" "$?" "3"

# --- R5: the repo-root guards were structurally DEAD - `cd ""` succeeds and does not move,
# so outside a repo they never fired (the rc=3 came from the enumeration failing later).
# Same `cd ""` class fixed in the 2.4 block; the instance was fixed there, the class was not.
_nr="$P6W/notarepo"; mkdir -p "$_nr"
chk "--working outside a git repo names the real reason" \
    "$(cd "$_nr" && bash "$SCAN" --working 2>&1 >/dev/null | grep -c 'requires a git repository')" "1"
chk "--staged outside a git repo names the real reason" \
    "$(cd "$_nr" && bash "$SCAN" --staged 2>&1 >/dev/null | grep -c 'requires a git repository')" "1"

# ===========================================================================
echo
echo "== PART 7: round-6 review fixes (every case measured 2026-08-03) =="
P7W="$WORK/p7"; mkdir -p "$P7W"

# --- R6: the non-regular accounting must key on WHAT THE ENTRY IS, not WHO NAMED IT. Round 5
# keyed it on MODE, but CI and the god-review 2.4 block both ENUMERATE via `git ls-files` and
# then pass the result as EXPLICIT PATHS - so a batch that happened to hold only gitlinks
# returned rc=3 and would have turned CI red on a perfectly valid repository.
_r6="$P7W/main"; _r6sub="$P7W/sub"
( git init -q "$_r6sub" && cd "$_r6sub" && git config user.email t@t.invalid && git config user.name t \
  && printf 'x\n' > f && git add f && git commit -qm s ) >/dev/null 2>&1
( git init -q "$_r6" && cd "$_r6" && git config user.email t@t.invalid && git config user.name t \
  && printf 'base\n' > base.txt && git add base.txt && git commit -qm i ) >/dev/null 2>&1
_r6sha=$( cd "$_r6sub" && git rev-parse HEAD )
( cd "$_r6" && mkdir -p m1 m2 \
  && git update-index --add --cacheinfo "160000,$_r6sha,m1" \
  && git update-index --add --cacheinfo "160000,$_r6sha,m2" ) >/dev/null 2>&1
( cd "$_r6" && bash "$SCAN" -- m1 m2 >/dev/null 2>&1 )
chk "an explicit batch of ONLY gitlinks is rc=0 (CI cannot go red on a valid repo)" "$?" "0"
# ...but a plain directory the caller NAMED is still not accounted for.
mkdir -p "$_r6/plaindir"
( cd "$_r6" && bash "$SCAN" plaindir >/dev/null 2>&1 )
chk "a lone PLAIN directory argument is still rc=3" "$?" "3"
# ...and specifically a directory whose FIRST indexed entry is a gitlink. `git ls-files -s --
# <dir>` treats the path as a PATHSPEC and lists contents recursively, so the round-6 probe
# read the gitlink and counted the whole DIRECTORY as accounted - returning rc=0 CLEAN with a
# real key sitting inside it. The case above uses an EMPTY dir and could not see that.
mkdir -p "$_r6/pkg/m"
printf 'k=sk-%s\n' "$(python3 -c "print('A'*44)")" > "$_r6/pkg/zsecret.txt"
( cd "$_r6" && git add pkg/zsecret.txt >/dev/null 2>&1 \
  && git update-index --add --cacheinfo "160000,$_r6sha,pkg/m" ) >/dev/null 2>&1
( cd "$_r6" && bash "$SCAN" -- pkg >/dev/null 2>&1 )
chk "a directory hiding a secret behind a gitlink is rc=3, never clean" "$?" "3"
( cd "$_r6" && bash "$SCAN" -- pkg/m >/dev/null 2>&1 )
chk "the gitlink entry ITSELF is still accounted for (rc=0)" "$?" "0"

# --- R6: the 2.4 scan block enumerated with a bare `git ls-files`, which lists ONLY TRACKED
# files - so a real token in a brand-new UNTRACKED file was skipped and it printed "clean".
# That was a coverage regression against the recursive `find` it replaced, and untracked is
# exactly where a freshly-pasted credential lives.
chk "2.4 enumerates untracked files too (--cached --others)" \
    "$(grep -c 'ls-files -z --cached --others --exclude-standard' "$REPO/commands/god-review/principles/secret-leak.md")" "1"

# --- R6: dotfiles-sync ignored `git add -A`'s status while treating "nothing staged" as
# benign, so a FAILED staging looked exactly like a clean tree: exit 0, NO pause marker, and
# the edit never reached the remote. MEASURED: an untracked nested repo makes `git add -A`
# exit 128 and stage nothing at all - the very shape round 5 taught the scanner to tolerate.
chk "dotfiles-sync checks git add -A and fails loudly" \
    "$(grep -c 'if git add -A; then _add_ok=1; break; fi' "$REPO/scripts/dotfiles-sync.sh")" "1"
# ...but RETRIES first. This script runs from an async hook, so two invocations overlap
# routinely and an ordinary .git/index.lock collision is expected. Pausing on the FIRST
# failure turned a transient collision into a durable halt while the winning run pushed
# fine - the false-positive direction that has already failed three times in this arc.
chk "dotfiles-sync retries a transient index.lock before pausing" \
    "$(grep -c 'for _try in 1 2 3 4 5; do' "$REPO/scripts/dotfiles-sync.sh")" "1"
chk "dotfiles-sync pauses rather than silently delivering nothing" \
    "$(grep -c 'git add -A failed after retries' "$REPO/scripts/dotfiles-sync.sh")" "1"
# Behavioural: `git add -A` really does fail on this shape, so the guard has a live trigger.
_ga="$P7W/ga"; mkdir -p "$_ga"
( cd "$_ga" && git init -q . && git config user.email t@t.invalid && git config user.name t \
  && printf 'b\n' > base.txt && git add base.txt && git commit -qm i \
  && printf 'edit\n' > edit.txt && mkdir nested && cd nested && git init -q . ) >/dev/null 2>&1
( cd "$_ga" && git add -A >/dev/null 2>&1 )
chk "git add -A really does fail on an untracked nested repo (guard has a live trigger)" \
    "$([ "$?" -ne 0 ] && echo fails || echo succeeds)" "fails"

# --- R2: the consumer count drifted inside the very commit that forbade drifting.
# The pattern is ASSEMBLED from fragments so this check cannot match its own source - the
# first draft grepped for a literal and found ITSELF, reporting a defect that did not
# exist. Same self-matching trap the fake credentials above are assembled to avoid.
_stale=$(printf '%s of the %s' 'hree' 'four')
chk "no stale consumer count remains in scripts/ or docs/" \
    "$(grep -ril "t$_stale" "$REPO/scripts" "$REPO/docs" 2>/dev/null | wc -l | tr -d ' ')" "0"

# ---------------------------------------------------------------------------
echo
echo "---- $PASS passed, $FAIL failed ----"
[ "$FAIL" -eq 0 ] || exit 1
exit 0
